### ISSUE TITLE
The build command does not work on bionic

### ISSUE THREAD

**Issue by camille-rodriguez** [canonical/charmcraft#102]
`charmcraft build` fails when ran on bionic. 

The error traceback:
2020-07-30 20:59:03,438  charmcraft.commands.build      DEBUG    :: Collecting PyYAML (from ops->-r /home/ubuntu/charm-iscsi-connector/requirements.txt (line 2))
2020-07-30 20:59:03,442  charmcraft.commands.build      DEBUG    ::   Cache entry deserialization failed, entry ignored
2020-07-30 20:59:03,527  charmcraft.commands.build      DEBUG    :: Installing collected packages: MarkupSafe, jinja2, PyYAML, ops
2020-07-30 20:59:03,580  charmcraft.commands.build      DEBUG    :: Exception:
2020-07-30 20:59:03,580  charmcraft.commands.build      DEBUG    :: Traceback (most recent call last):
2020-07-30 20:59:03,580  charmcraft.commands.build      DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
2020-07-30 20:59:03,581  charmcraft.commands.build      DEBUG    ::     status = self.run(options, args)
2020-07-30 20:59:03,581  charmcraft.commands.build      DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
2020-07-30 20:59:03,581  charmcraft.commands.build      DEBUG    ::     prefix=options.prefix_path,
2020-07-30 20:59:03,581  charmcraft.commands.build      DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
2020-07-30 20:59:03,581  charmcraft.commands.build      DEBUG    ::     **kwargs
2020-07-30 20:59:03,581  charmcraft.commands.build      DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
2020-07-30 20:59:03,581  charmcraft.commands.build      DEBUG    ::     self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
2020-07-30 20:59:03,581  charmcraft.commands.build      DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
2020-07-30 20:59:03,581  charmcraft.commands.build      DEBUG    ::     isolated=self.isolated,
2020-07-30 20:59:03,581  charmcraft.commands.build      DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
2020-07-30 20:59:03,581  charmcraft.commands.build      DEBUG    ::     prefix=prefix,
2020-07-30 20:59:03,582  charmcraft.commands.build      DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
2020-07-30 20:59:03,582  charmcraft.commands.build      DEBUG    ::     i.finalize_options()
2020-07-30 20:59:03,582  charmcraft.commands.build      DEBUG    ::   File "/usr/lib/python3.6/distutils/command/install.py", line 274, in finalize_options
2020-07-30 20:59:03,582  charmcraft.commands.build      DEBUG    ::     raise DistutilsOptionError("can't combine user with prefix, "
2020-07-30 20:59:03,582  charmcraft.commands.build      DEBUG    :: distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
2020-07-30 20:59:03,639  charmcraft.commands.build      ERROR    Executing ['pip3', 'install', '--target=/home/ubuntu/charm-iscsi-connector/build/venv', '--requirement=/home/ubuntu/charm-iscsi-connector/requirements.txt'] failed with return code 2
2020-07-30 20:59:03,640  charmcraft                     ERROR    problems installing dependencies (full execution logs in /tmp/charmcraft-log-8036vrqs)

**Comment by jameinel** [comment]
As a summary, 'pip install' on bionic overrides the defaults from pip to pass '--user' by default. However pip doesn't allow --target if you are using --user, and so the workaround is to pass '--system' which only exists on Bionic as a way to *disable* --user.
