### ISSUE TITLE
'raw.idmap=both 595156457 0' causes charmcraft to crash

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#1054]
```bash
$ charmcraft pack
$ charmcraft pack
charmcraft internal error: LXDError(brief="Failed to launch instance 'charmcraft-scania-hpc-2495015-0-0-amd64'.", details='* Command that failed: "lxc --project charmcraft launch craft-com.ubuntu.cloud-buildd:core22 local:charmcraft-scania-hpc-2495015-0-0-amd64 --config \'raw.idmap=both 595156457 0\' --config security.syscalls.intercept.mknod=true"\n* Command exit code: 1\n* Command output: b\'Creating charmcraft-scania-hpc-2495015-0-0-amd64\\n\'\n* Command standard error output: b\'Error: Failed instance creation: Failed creating instance record: Failed initialising instance: Host id is in the range of subids\\n\'', resolution=None)             
Full execution log: '/home/jbemfv/.local/state/charmcraft/log/charmcraft-20230326-114836.166218.log'   
```

```bash
$ cat /home/jbemfv/.local/state/charmcraft/log/charmcraft-20230326-114836.166218.log
2023-03-26 11:36:11.982 Starting charmcraft version 2.2.0
2023-03-26 11:36:11.985 System details: OSPlatform(system='ubuntu', release='20.04', machine='x86_64'); Environment: DESKTOP_SESSION='ubuntu', XDG_CURRENT_DESKTOP='ubuntu:GNOME'
2023-03-26 11:36:11.985 Packing the charm.
2023-03-26 11:36:11.986 Reading '/home/jbemfv/allcode/github/omnivector/charm-hpc/metadata.yaml'
2023-03-26 11:36:11.987 Validating metadata format
2023-03-26 11:36:12.127 Executing on host: lxc --project default profile show local:default
2023-03-26 11:36:12.225 Building for 'bases[0]' as host matches 'build-on[0]'.
2023-03-26 11:36:12.225 Building for 'bases[0][0]'.
2023-03-26 11:36:12.225 Launching environment to pack for base name='ubuntu' channel='22.04' architectures=['amd64'] (may take a while the first time but it's reusable)
2023-03-26 11:36:12.226 Using hostname 'charmcraft-hpc-2495015-0-0-amd64'
2023-03-26 11:36:12.226 Executing on host: lxc remote list --format=yaml
2023-03-26 11:36:12.321 Remote 'craft-com.ubuntu.cloud-buildd' already exists.
2023-03-26 11:36:12.321 Executing on host: lxc project list local: --format=yaml
2023-03-26 11:36:12.420 Set LXD instance name to 'charmcraft-hpc-2495015-0-0-amd64'
2023-03-26 11:36:12.420 Executing on host: lxc --project charmcraft list local: --format=yaml
2023-03-26 11:36:12.516 Executing on host: lxc --project charmcraft image list local: --format=yaml
2023-03-26 11:36:12.615 Executing on host: lxc --project charmcraft info local:
2023-03-26 11:36:12.735 Executing on host: lxc --project charmcraft launch craft-com.ubuntu.cloud-buildd:core22 local:charmcraft-hpc-2495015-0-0-amd64 --config 'raw.idmap=both 595156457 0' --config security.syscalls.intercept.mknod=true
2023-03-26 11:36:15.132 charmcraft internal error: LXDError(brief="Failed to launch instance 'charmcraft-hpc-2495015-0-0-amd64'.", details='* Command that failed: "lxc --project charmcraft launch craft-com.ubuntu.cloud-buildd:core22 local:charmcraft-hpc-2495015-0-0-amd64 --config \'raw.idmap=both 595156457 0\' --config security.syscalls.intercept.mknod=true"\n* Command exit code: 1\n* Command output: b\'Creating charmcraft-hpc-2495015-0-0-amd64\\n\\rRetrieving image: metadata: 1% (7.33MB/s)\\rRetrieving image: metadata: 2% (12.97MB/s)\\r                                           \\rRetrieving image: metadata: 3% (18.10MB/s)\\r                                           \\rRetrieving image: metadata: 4% (23.10MB/s)\\r                                           \\rRetrieving image: metadata: 5% (27.14MB/s)\\r                                           \\rRetrieving image: metadata: 6% (31.05MB/s)\\r                                           \\rRetrieving image: metadata: 7% (34.33MB/s)\\r                                           \\rRetrieving image: metadata: 8% (37.18MB/s)\\r                                           \\rRetrieving image: metadata: 9% (40.26MB/s)\\rRetrieving image: metadata: 10% (42.38MB/s)\\r                                            \\rRetrieving image: metadata: 10% (45.22MB/s)\\r                                            \\rRetrieving image: metadata: 11% (46.96MB/s)\\r                                            \\rRetrieving image: metadata: 12% (49.29MB/s)\\r                                            \\rRetrieving image: metadata: 13% (50.85MB/s)\\r                                            \\rRetrieving image: metadata: 14% (52.54MB/s)\\r                                            \\rRetrieving image: metadata: 15% (53.96MB/s)\\r                                            \\rRetrieving image: metadata: 16% (55.51MB/s)\\r                                            \\rRetrieving image: metadata: 17% (56.64MB/s)\\r                                            \\rRetrieving image: metadata: 18% (58.55MB/s)\\r                                            \\rRetrieving image: metadata: 19% (59.20MB/s)\\r                                            \\rRetrieving image: metadata: 20% (60.51MB/s)\\r                                            \\rRetrieving image: metadata: 20% (62.04MB/s)\\r                                            \\rRetrieving image: metadata: 21% (62.33MB/s)\\r                                            \\rRetrieving image: metadata: 22% (63.46MB/s)\\r                                            \\rRetrieving image: metadata: 23% (63.86MB/s)\\r                                            \\rRetrieving image: metadata: 24% (65.23MB/s)\\r                                            \\rRetrieving image: metadata: 25% (66.07MB/s)\\r                                            \\rRetrieving image: metadata: 26% (66.75MB/s)\\r                                            \\rRetrieving image: metadata: 27% (67.59MB/s)\\r                                            \\rRetrieving image: metadata: 28% (68.14MB/s)\\r                                            \\rRetrieving image: metadata: 29% (68.98MB/s)\\r                                            \\rRetrieving image: metadata: 30% (69.35MB/s)\\r                                            \\rRetrieving image: metadata: 30% (70.30MB/s)\\r                                            \\rRetrieving image: metadata: 31% (70.47MB/s)\\r                                            \\rRetrieving image: metadata: 32% (71.54MB/s)\\r                                            \\rRetrieving image: metadata: 33% (71.70MB/s)\\r                                            \\rRetrieving image: metadata: 34% (72.55MB/s)\\r                                            \\rRetrieving image: metadata: 35% (72.95MB/s)\\r                                            \\rRetrieving image: metadata: 36% (73.42MB/s)\\r                                            \\rRetrieving image: metadata: 37% (74.26MB/s)\\r                                            \\rRetrieving image: metadata: 38% (74.12MB/s)\\r                                            \\rRetrieving image: metadata: 39% (74.96MB/s)\\r                                            \\rRetrieving image: metadata: 40% (74.88MB/s)\\r                                            \\rRetrieving image: metadata: 40% (75.60MB/s)\\r                                            \\rRetrieving image: metadata: 41% (75.99MB/s)\\r                                            \\rRetrieving image: metadata: 42% (76.10MB/s)\\r                                            \\rRetrieving image: metadata: 43% (76.73MB/s)\\r                                            \\rRetrieving image: metadata: 44% (76.75MB/s)\\r                                            \\rRetrieving image: metadata: 45% (77.41MB/s)\\r                                            \\rRetrieving image: metadata: 46% (77.56MB/s)\\r                                            \\rRetrieving image: metadata: 47% (78.06MB/s)\\r                                            \\rRetrieving image: metadata: 48% (78.30MB/s)\\r                                            \\rRetrieving image: metadata: 49% (78.50MB/s)\\r                                            \\rRetrieving image: metadata: 50% (78.89MB/s)\\r                                            \\rRetrieving image: metadata: 50% (78.91MB/s)\\r                                            \\rRetrieving image: metadata: 51% (79.53MB/s)\\r                                            \\rRetrieving image: metadata: 52% (79.64MB/s)\\r                                            \\rRetrieving image: metadata: 53% (79.99MB/s)\\r                                            \\rRetrieving image: metadata: 54% (80.35MB/s)\\r                                            \\rRetrieving image: metadata: 55% (80.19MB/s)\\r                                            \\rRetrieving image: metadata: 56% (80.80MB/s)\\r                                            \\rRetrieving image: metadata: 57% (80.47MB/s)\\r                                            \\rRetrieving image: metadata: 58% (81.07MB/s)\\r                                            \\rRetrieving image: metadata: 59% (80.95MB/s)\\r                                            \\rRetrieving image: metadata: 60% (81.24MB/s)\\r                                            \\rRetrieving image: metadata: 60% (81.68MB/s)\\r                                            \\rRetrieving image: metadata: 61% (81.41MB/s)\\r                                            \\rRetrieving image: metadata: 62% (81.96MB/s)\\r                                            \\rRetrieving image: metadata: 63% (81.92MB/s)\\r                                            \\rRetrieving image: metadata: 64% (82.07MB/s)\\r                                            \\rRetrieving image: metadata: 65% (82.23MB/s)\\r                                            \\rRetrieving image: metadata: 66% (82.34MB/s)\\r                                            \\rRetrieving image: metadata: 67% (82.78MB/s)\\r                                            \\rRetrieving image: metadata: 68% (82.68MB/s)\\r                                            \\rRetrieving image: metadata: 69% (83.02MB/s)\\r                                            \\rRetrieving image: metadata: 70% (83.07MB/s)\\r                                            \\rRetrieving image: metadata: 70% (83.13MB/s)\\r                                            \\rRetrieving image: metadata: 71% (83.34MB/s)\\r                                            \\rRetrieving image: metadata: 72% (83.23MB/s)\\r                                            \\rRetrieving image: metadata: 73% (83.67MB/s)\\r                                            \\rRetrieving image: metadata: 74% (83.60MB/s)\\r                                            \\rRetrieving image: metadata: 75% (83.88MB/s)\\r                                            \\rRetrieving image: metadata: 76% (83.89MB/s)\\r                                            \\rRetrieving image: metadata: 77% (84.00MB/s)\\r                                            \\rRetrieving image: metadata: 78% (84.23MB/s)\\r                                            \\rRetrieving image: metadata: 79% (84.46MB/s)\\r                                            \\rRetrieving image: metadata: 80% (84.61MB/s)\\r                                            \\rRetrieving image: metadata: 80% (84.65MB/s)\\r                                            \\rRetrieving image: metadata: 81% (84.90MB/s)\\r                                            \\rRetrieving image: metadata: 82% (84.82MB/s)\\r                                            \\rRetrieving image: metadata: 83% (85.15MB/s)\\r                                            \\rRetrieving image: metadata: 84% (85.05MB/s)\\r                                            \\rRetrieving image: metadata: 85% (85.33MB/s)\\r                                            \\rRetrieving image: metadata: 86% (85.38MB/s)\\r                                            \\rRetrieving image: metadata: 87% (85.36MB/s)\\r                                            \\rRetrieving image: metadata: 88% (85.67MB/s)\\r                                            \\rRetrieving image: metadata: 89% (85.43MB/s)\\r                                            \\rRetrieving image: metadata: 90% (85.78MB/s)\\r                                            \\rRetrieving image: metadata: 91% (85.64MB/s)\\r                                            \\rRetrieving image: metadata: 91% (85.88MB/s)\\r                                            \\rRetrieving image: metadata: 92% (85.83MB/s)\\r                                            \\rRetrieving image: metadata: 93% (86.08MB/s)\\r                                            \\rRetrieving image: metadata: 94% (86.06MB/s)\\r                                            \\rRetrieving image: metadata: 95% (86.33MB/s)\\r                                            \\rRetrieving image: metadata: 96% (86.40MB/s)\\r                                            \\rRetrieving image: metadata: 97% (86.54MB/s)\\r                                            \\rRetrieving image: metadata: 98% (86.74MB/s)\\r                                            \\rRetrieving image: metadata: 99% (86.67MB/s)\\rRetrieving image: metadata: 100% (86.86MB/s)\\r                                             \\rRetrieving image: metadata: 100% (86.73MB/s)\\r                                             \\rRetrieving image: metadata: 100% (86.73MB/s)\\r                                             \\r\'\n* Command standard error output: b\'Error: Failed instance creation: Failed creating instance record: Failed initialising instance: Host id is in the range of subids\\n\'', resolution=None)
2023-03-26 11:36:15.134 Traceback (most recent call last):
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/craft_providers/lxd/lxc.py", line 549, in launch
2023-03-26 11:36:15.134     self._run_lxc(
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/craft_providers/lxd/lxc.py", line 98, in _run_lxc
2023-03-26 11:36:15.134     return subprocess.run(lxc_cmd, check=check, stdin=stdin.value, **kwargs)
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/usr/lib/python3.8/subprocess.py", line 516, in run
2023-03-26 11:36:15.134     raise CalledProcessError(retcode, process.args,
2023-03-26 11:36:15.134 subprocess.CalledProcessError: Command '['lxc', '--project', 'charmcraft', 'launch', 'craft-com.ubuntu.cloud-buildd:core22', 'local:charmcraft-hpc-2495015-0-0-amd64', '--config', 'raw.idmap=both 595156457 0', '--config', 'security.syscalls.intercept.mknod=true']' returned non-zero exit status 1.
2023-03-26 11:36:15.134 
2023-03-26 11:36:15.134 The above exception was the direct cause of the following exception:
2023-03-26 11:36:15.134 Traceback (most recent call last):
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/charmcraft/main.py", line 184, in main
2023-03-26 11:36:15.134     retcode = dispatcher.run()
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/craft_cli/dispatcher.py", line 448, in run
2023-03-26 11:36:15.134     return self._loaded_command.run(self._parsed_command_args)
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/charmcraft/commands/pack.py", line 133, in run
2023-03-26 11:36:15.134     pack_method(parsed_args)
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/charmcraft/commands/pack.py", line 165, in _pack_charm
2023-03-26 11:36:15.134     charms = builder.run(
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/charmcraft/instrum.py", line 152, in _f
2023-03-26 11:36:15.134     return func(*args, **kwargs)
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/charmcraft/commands/build.py", line 292, in run
2023-03-26 11:36:15.134     charm_name = self.pack_charm_in_instance(
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/charmcraft/commands/build.py", line 357, in pack_charm_in_instance
2023-03-26 11:36:15.134     with self.provider.launched_environment(
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/usr/lib/python3.8/contextlib.py", line 113, in __enter__
2023-03-26 11:36:15.134     return next(self.gen)
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/craft_providers/lxd/lxd_provider.py", line 126, in launched_environment
2023-03-26 11:36:15.134     instance = launch(
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/craft_providers/lxd/launcher.py", line 205, in launch
2023-03-26 11:36:15.134     instance.launch(
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/craft_providers/lxd/lxd_instance.py", line 407, in launch
2023-03-26 11:36:15.134     self.lxc.launch(
2023-03-26 11:36:15.134   File "/snap/charmcraft/1171/lib/craft_providers/lxd/lxc.py", line 557, in launch
2023-03-26 11:36:15.134     raise LXDError(
2023-03-26 11:36:15.134 craft_providers.lxd.errors.LXDError: Failed to launch instance 'charmcraft-hpc-2495015-0-0-amd64'.
2023-03-26 11:36:15.134 * Command that failed: "lxc --project charmcraft launch craft-com.ubuntu.cloud-buildd:core22 local:charmcraft-hpc-2495015-0-0-amd64 --config 'raw.idmap=both 595156457 0' --config security.syscalls.intercept.mknod=true"
2023-03-26 11:36:15.134 * Command exit code: 1
2023-03-26 11:36:15.134 * Command output: b'Creating charmcraft-hpc-2495015-0-0-amd64\n\rRetrieving image: metadata: 1% (7.33MB/s)\rRetrieving image: metadata: 2% (12.97MB/s)\r                                           \rRetrieving image: metadata: 3% (18.10MB/s)\r                                           \rRetrieving image: metadata: 4% (23.10MB/s)\r                                           \rRetrieving image: metadata: 5% (27.14MB/s)\r                                           \rRetrieving image: metadata: 6% (31.05MB/s)\r                                           \rRetrieving image: metadata: 7% (34.33MB/s)\r                                           \rRetrieving image: metadata: 8% (37.18MB/s)\r                                           \rRetrieving image: metadata: 9% (40.26MB/s)\rRetrieving image: metadata: 10% (42.38MB/s)\r                                            \rRetrieving image: metadata: 10% (45.22MB/s)\r                                            \rRetrieving image: metadata: 11% (46.96MB/s)\r                                            \rRetrieving image: metadata: 12% (49.29MB/s)\r                                            \rRetrieving image: metadata: 13% (50.85MB/s)\r                                            \rRetrieving image: metadata: 14% (52.54MB/s)\r                                            \rRetrieving image: metadata: 15% (53.96MB/s)\r                                            \rRetrieving image: metadata: 16% (55.51MB/s)\r                                            \rRetrieving image: metadata: 17% (56.64MB/s)\r                                            \rRetrieving image: metadata: 18% (58.55MB/s)\r                                            \rRetrieving image: metadata: 19% (59.20MB/s)\r                                            \rRetrieving image: metadata: 20% (60.51MB/s)\r                                            \rRetrieving image: metadata: 20% (62.04MB/s)\r                                            \rRetrieving image: metadata: 21% (62.33MB/s)\r                                            \rRetrieving image: metadata: 22% (63.46MB/s)\r                                            \rRetrieving image: metadata: 23% (63.86MB/s)\r                                            \rRetrieving image: metadata: 24% (65.23MB/s)\r                                            \rRetrieving image: metadata: 25% (66.07MB/s)\r                                            \rRetrieving image: metadata: 26% (66.75MB/s)\r                                            \rRetrieving image: metadata: 27% (67.59MB/s)\r                                            \rRetrieving image: metadata: 28% (68.14MB/s)\r                                            \rRetrieving image: metadata: 29% (68.98MB/s)\r                                            \rRetrieving image: metadata: 30% (69.35MB/s)\r                                            \rRetrieving image: metadata: 30% (70.30MB/s)\r                                            \rRetrieving image: metadata: 31% (70.47MB/s)\r                                            \rRetrieving image: metadata: 32% (71.54MB/s)\r                                            \rRetrieving image: metadata: 33% (71.70MB/s)\r                                            \rRetrieving image: metadata: 34% (72.55MB/s)\r                                            \rRetrieving image: metadata: 35% (72.95MB/s)\r                                            \rRetrieving image: metadata: 36% (73.42MB/s)\r                                            \rRetrieving image: metadata: 37% (74.26MB/s)\r                                            \rRetrieving image: metadata: 38% (74.12MB/s)\r                                            \rRetrieving image: metadata: 39% (74.96MB/s)\r                                            \rRetrieving image: metadata: 40% (74.88MB/s)\r                                            \rRetrieving image: metadata: 40% (75.60MB/s)\r                                            \rRetrieving image: metadata: 41% (75.99MB/s)\r                                            \rRetrieving image: metadata: 42% (76.10MB/s)\r                                            \rRetrieving image: metadata: 43% (76.73MB/s)\r                                            \rRetrieving image: metadata: 44% (76.75MB/s)\r                                            \rRetrieving image: metadata: 45% (77.41MB/s)\r                                            \rRetrieving image: metadata: 46% (77.56MB/s)\r                                            \rRetrieving image: metadata: 47% (78.06MB/s)\r                                            \rRetrieving image: metadata: 48% (78.30MB/s)\r                                            \rRetrieving image: metadata: 49% (78.50MB/s)\r                                            \rRetrieving image: metadata: 50% (78.89MB/s)\r                                            \rRetrieving image: metadata: 50% (78.91MB/s)\r                                            \rRetrieving image: metadata: 51% (79.53MB/s)\r                                            \rRetrieving image: metadata: 52% (79.64MB/s)\r                                            \rRetrieving image: metadata: 53% (79.99MB/s)\r                                            \rRetrieving image: metadata: 54% (80.35MB/s)\r                                            \rRetrieving image: metadata: 55% (80.19MB/s)\r                                            \rRetrieving image: metadata: 56% (80.80MB/s)\r                                            \rRetrieving image: metadata: 57% (80.47MB/s)\r                                            \rRetrieving image: metadata: 58% (81.07MB/s)\r                                            \rRetrieving image: metadata: 59% (80.95MB/s)\r                                            \rRetrieving image: metadata: 60% (81.24MB/s)\r                                            \rRetrieving image: metadata: 60% (81.68MB/s)\r                                            \rRetrieving image: metadata: 61% (81.41MB/s)\r                                            \rRetrieving image: metadata: 62% (81.96MB/s)\r                                            \rRetrieving image: metadata: 63% (81.92MB/s)\r                                            \rRetrieving image: metadata: 64% (82.07MB/s)\r                                            \rRetrieving image: metadata: 65% (82.23MB/s)\r                                            \rRetrieving image: metadata: 66% (82.34MB/s)\r                                            \rRetrieving image: metadata: 67% (82.78MB/s)\r                                            \rRetrieving image: metadata: 68% (82.68MB/s)\r                                            \rRetrieving image: metadata: 69% (83.02MB/s)\r                                            \rRetrieving image: metadata: 70% (83.07MB/s)\r                                            \rRetrieving image: metadata: 70% (83.13MB/s)\r                                            \rRetrieving image: metadata: 71% (83.34MB/s)\r                                            \rRetrieving image: metadata: 72% (83.23MB/s)\r                                            \rRetrieving image: metadata: 73% (83.67MB/s)\r                                            \rRetrieving image: metadata: 74% (83.60MB/s)\r                                            \rRetrieving image: metadata: 75% (83.88MB/s)\r                                            \rRetrieving image: metadata: 76% (83.89MB/s)\r                                            \rRetrieving image: metadata: 77% (84.00MB/s)\r                                            \rRetrieving image: metadata: 78% (84.23MB/s)\r                                            \rRetrieving image: metadata: 79% (84.46MB/s)\r                                            \rRetrieving image: metadata: 80% (84.61MB/s)\r                                            \rRetrieving image: metadata: 80% (84.65MB/s)\r                                            \rRetrieving image: metadata: 81% (84.90MB/s)\r                                            \rRetrieving image: metadata: 82% (84.82MB/s)\r                                            \rRetrieving image: metadata: 83% (85.15MB/s)\r                                            \rRetrieving image: metadata: 84% (85.05MB/s)\r                                            \rRetrieving image: metadata: 85% (85.33MB/s)\r                                            \rRetrieving image: metadata: 86% (85.38MB/s)\r                                            \rRetrieving image: metadata: 87% (85.36MB/s)\r                                            \rRetrieving image: metadata: 88% (85.67MB/s)\r                                            \rRetrieving image: metadata: 89% (85.43MB/s)\r                                            \rRetrieving image: metadata: 90% (85.78MB/s)\r                                            \rRetrieving image: metadata: 91% (85.64MB/s)\r                                            \rRetrieving image: metadata: 91% (85.88MB/s)\r                                            \rRetrieving image: metadata: 92% (85.83MB/s)\r                                            \rRetrieving image: metadata: 93% (86.08MB/s)\r                                            \rRetrieving image: metadata: 94% (86.06MB/s)\r                                            \rRetrieving image: metadata: 95% (86.33MB/s)\r                                            \rRetrieving image: metadata: 96% (86.40MB/s)\r                                            \rRetrieving image: metadata: 97% (86.54MB/s)\r                                            \rRetrieving image: metadata: 98% (86.74MB/s)\r                                            \rRetrieving image: metadata: 99% (86.67MB/s)\rRetrieving image: metadata: 100% (86.86MB/s)\r                                             \rRetrieving image: metadata: 100% (86.73MB/s)\r                                             \rRetrieving image: metadata: 100% (86.73MB/s)\r                                             \r'
2023-03-26 11:36:15.134 * Command standard error output: b'Error: Failed instance creation: Failed creating instance record: Failed initialising instance: Host id is in the range of subids\n'
2023-03-26 11:36:15.134 Full execution log: '/home/jbemfv/.local/state/charmcraft/log/charmcraft-20230326-113611.981755.log'
```

Launching lxd by hand works just fine:

```bash
$ lxc launch ubuntu:22.04 u2
Creating u2
Starting u2 
```

Something tells me `'raw.idmap=both 595156457 0'` is causing havoc here.

How can I investigate this further?

**Comment by sergiusens** [comment]
This is probably NIS related; @tomponline any ideas or thoughts?

**Comment by tomponline** [comment]
@sergiusens apologies for the delay. @stgraber do you have any ideas on this issue? Thanks

**Comment by stgraber** [comment]
Can you file an issue at https://github.com/lxc/lxd/issues?

**Comment by tomponline** [comment]
@sergiusens @mr-cal please can you show the output of `lxc config show <instance> --expanded`, as it looks like the issue is intersecting uids.

**Comment by tomponline** [comment]
Filed issue https://github.com/lxc/lxd/issues/11600 so we can keep track of it.

**Comment by tomponline** [comment]
@sergiusens @mr-cal @jamesbeedy does this forum post solve the issue?

https://discourse.charmhub.io/t/using-charmcraft-with-very-high-uids/7208

**Comment by mr-cal** [comment]
Thanks for finding that forum post @tomponline!  I created an [issue](https://github.com/canonical/craft-providers/issues/259) in craft-providers where this failing scenario should be handled.

Until craft-providers is fixed, I'm fine to leave this issue open so others can find the workarounds in that forum post.

**Comment by jamesbeedy** [comment]
> @sergiusens @mr-cal @jamesbeedy does this forum post solve the issue?
> 
> https://discourse.charmhub.io/t/using-charmcraft-with-very-high-uids/7208

This entirely solves my problem! Thank you for the reference @tomponline and @hallback for finding a way through there!
