### ISSUE TITLE
Can't build the same charm in parallel

### ISSUE THREAD

**Issue by knkski** [canonical/charmcraft#164]
If I'm building one charm on the same machine in different processes, one of the builds will fail due to each charmcraft build process using the same build directory, and removing it after it's done. The traceback that I get:

```python
Traceback (most recent call last):
  File "/snap/charmcraft/97/lib/charmcraft/main.py", line 191, in main
    dispatcher.run()
  File "/snap/charmcraft/97/lib/charmcraft/main.py", line 121, in run
    command.run(self.parsed_args)
  File "/snap/charmcraft/97/lib/charmcraft/commands/build.py", line 390, in run
    builder.run()
  File "/snap/charmcraft/97/lib/charmcraft/commands/build.py", line 105, in run
    shutil.rmtree(str(self.buildpath))
  File "/usr/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.8/shutil.py", line 652, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.8/shutil.py", line 652, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.8/shutil.py", line 652, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.8/shutil.py", line 672, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 670, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'namedtype.py'
```
Since `charmcraft build` results in a `*.charm` file dropped in the current directory, instead of a directory that users need to interact with, it seems like we could just use `tempfile.TemporaryDirectory` instead of basing the build directory on the charm name.

**Comment by facundobatista** [comment]
Hello @knkski,

Why are you building the same charm twice? I foresee not even a problem with the build directory, but as the resulting file is `<name>.charm`, one will overlap the other.

Or you're working from two different dirs, but calling to the same charm?

Would you mind to explain a little more which is your use case, and how you're executing those two runs in parallel? Thanks!!!

**Comment by facundobatista** [comment]
Hello @knkski,

We're discussing something very similar to this in issue #103, and we did change the behaviour related to this in last weeks.

Are you still needing a change here? We're not understanding exactly the use case, we think that is already fixed or duplicate from that bug, so will close this one.

Thanks,

**Comment by facundobatista** [comment]
Closing this for lack of information.
