### ISSUE TITLE
internal error: TypeError("'NoneType' object is not iterable") when running charmcraft login

### ISSUE THREAD

**Issue by Thanhphan1147** [canonical/charmcraft#1667]
### Bug Description

Hi, when I run `charmcraft login` on the edge channel, I get this message `internal error: TypeError("'NoneType' object is not iterable")`.

I switched to stable and the issue seems to went away.

### To Reproduce

```
sudo snap install charmcraft --classic --channel=latest/edge
charmcraft login
```

### Environment

```
$ sudo snap info charmcraft                         
name:      charmcraft
summary:   The charming tool
publisher: Canonical✓
store-url: https://snapcraft.io/charmcraft
license:   Apache-2.0
description: |
  Charmcraft enables charm creators to build, publish, and manage charmed operators for Kubernetes,
  metal and virtual machines.
commands:
  - charmcraft
snap-id:      gcqfpVCOUvmDuYT0Dh5PjdeGypSEzNdV
tracking:     latest/edge
refresh-date: today at 20:39 CEST
channels:
  latest/stable:    2.6.0                  2024-04-12 (3451) 29MB classic
  latest/candidate: 2.6.0                  2024-04-11 (3454) 29MB classic
  latest/beta:      2.6.0                  2024-04-13 (3518) 29MB classic
  latest/edge:      3.0.0.post28+gb3d35e6  2024-04-24 (3626) 36MB classic
  3.x/stable:       –                                             
  3.x/candidate:    –                                             
  3.x/beta:         3.0.0                  2024-03-15 (3246) 35MB classic
  3.x/edge:         3.0.0.post28+gb3d35e6  2024-04-24 (3626) 36MB classic
  2.x/stable:       2.6.0                  2024-04-12 (3451) 29MB classic
  2.x/candidate:    2.6.0                  2024-04-13 (3518) 29MB classic
  2.x/beta:         2.6.0                  2024-04-13 (3518) 29MB classic
  2.x/edge:         2.6.0.post1+gitd4d5da9 2024-04-15 (3537) 30MB classic
  2.5/stable:       –                                             
  2.5/candidate:    –                                             
  2.5/beta:         –                                             
  2.5/edge:         2.5.5.post5+git5ee6169 2024-02-01 (2538) 29MB classic
  2.2/stable:       2.2.0                  2023-01-11 (1171) 59MB classic
  2.2/candidate:    ↑                                             
  2.2/beta:         ↑                                             
  2.2/edge:         ↑                                             
  2.1/stable:       2.1.0                  2022-10-11 (1083) 59MB classic
  2.1/candidate:    ↑                                             
  2.1/beta:         ↑                                             
  2.1/edge:         ↑                                             
  2.0/stable:       2.0.0                  2022-08-01 (1033) 59MB classic
  2.0/candidate:    ↑                                             
  2.0/beta:         ↑                                             
  2.0/edge:         ↑                                             
  1.x/stable:       1.7.1                  2022-06-09  (978) 59MB classic
  1.x/candidate:    ↑                                             
  1.x/beta:         ↑                                             
  1.x/edge:         ↑                                             
  1.7/stable:       1.7.1                  2022-06-09  (978) 59MB classic
  1.7/candidate:    ↑                                             
  1.7/beta:         ↑                                             
  1.7/edge:         ↑                                             
  1.6/stable:       1.6.0                  2022-04-20  (904) 59MB classic
  1.6/candidate:    ↑                                             
  1.6/beta:         ↑                                             
  1.6/edge:         ↑                                             
  1.5/stable:       1.5.0                  2022-04-13  (834) 59MB classic
  1.5/candidate:    ↑                                             
  1.5/beta:         ↑                                             
  1.5/edge:         ↑                                             
installed:          3.0.0.post28+gb3d35e6             (3626) 36MB classic
```

### charmcraft.yaml

```shell
N/A
```

### Relevant log output

```shell
charmcraft internal error: TypeError("'NoneType' object is not iterable")                                                                                                                                  
Full execution log: '/home/tphan025/.local/state/charmcraft/log/charmcraft-20240424-203438.864585.log'  

$ cat /home/tphan025/.local/state/charmcraft/log/charmcraft-20240424-203357.209634.log            
2024-04-24 20:33:57.217 Starting charmcraft, version 3.0.0.post28+gb3d35e6
2024-04-24 20:33:57.217 Log verbosity level set to BRIEF
2024-04-24 20:33:57.217 Configuring application...
2024-04-24 20:33:57.218 Preparing application...
2024-04-24 20:33:57.219 Build plan: platform=None, build_for=None
2024-04-24 20:33:57.219 Running charmcraft login on host
2024-04-24 20:33:57.219 charmcraft internal error: TypeError("'NoneType' object is not iterable")
2024-04-24 20:33:57.222 Traceback (most recent call last):
2024-04-24 20:33:57.222   File "/snap/charmcraft/3626/lib/python3.10/site-packages/craft_application/application.py", line 510, in run
2024-04-24 20:33:57.222     return_code = dispatcher.run() or 0
2024-04-24 20:33:57.222   File "/snap/charmcraft/3626/lib/python3.10/site-packages/craft_cli/dispatcher.py", line 487, in run
2024-04-24 20:33:57.222     return self._loaded_command.run(self._parsed_command_args)
2024-04-24 20:33:57.222   File "/snap/charmcraft/3626/lib/python3.10/site-packages/charmcraft/application/commands/store.py", line 189, in run
2024-04-24 20:33:57.222     packages = utils.get_packages(charms=parsed_args.charm, bundles=parsed_args.bundle) or None
2024-04-24 20:33:57.222   File "/snap/charmcraft/3626/lib/python3.10/site-packages/charmcraft/utils/store.py", line 28, in get_packages
2024-04-24 20:33:57.222     *(endpoints.Package(package_type="bundle", package_name=bundle) for bundle in bundles),
2024-04-24 20:33:57.222 TypeError: 'NoneType' object is not iterable
2024-04-24 20:33:57.222 Full execution log: '/home/tphan025/.local/state/charmcraft/log/charmcraft-20240424-203357.209634.log'
```

**Comment by lengau** [comment]
Thanks for the report! This is fixed.
