### ISSUE TITLE
Charmcraft login fails

### ISSUE THREAD

**Issue by jdkandersson** [canonical/charmcraft#1672]
### Bug Description

when running `charmcraft login` I get the error `TypeError: 'NoneType' object is not iterable`

### To Reproduce

Create a multipass VM, install `latest/edge` of charmcraft and run `charmcraft login`

### Environment

Mac OSX running multipass jammy

### charmcraft.yaml

```shell
N/A
```

### Relevant log output

```shell
cat /home/ubuntu/.local/state/charmcraft/log/charmcraft-20240508-225306.757877.log
2024-05-08 22:53:06.759 Starting charmcraft, version 3.0.0.post30+gb2b127e
2024-05-08 22:53:06.759 Log verbosity level set to BRIEF
2024-05-08 22:53:06.759 Configuring application...
2024-05-08 22:53:06.759 Preparing application...
2024-05-08 22:53:06.760 Build plan: platform=None, build_for=None
2024-05-08 22:53:06.761 Running charmcraft login on host
2024-05-08 22:53:06.761 charmcraft internal error: TypeError("'NoneType' object is not iterable")
2024-05-08 22:53:06.764 Traceback (most recent call last):
2024-05-08 22:53:06.764   File "/snap/charmcraft/3663/lib/python3.10/site-packages/craft_application/application.py", line 510, in run
2024-05-08 22:53:06.764     return_code = dispatcher.run() or 0
2024-05-08 22:53:06.764   File "/snap/charmcraft/3663/lib/python3.10/site-packages/craft_cli/dispatcher.py", line 487, in run
2024-05-08 22:53:06.764     return self._loaded_command.run(self._parsed_command_args)
2024-05-08 22:53:06.764   File "/snap/charmcraft/3663/lib/python3.10/site-packages/charmcraft/application/commands/store.py", line 190, in run
2024-05-08 22:53:06.764     packages = utils.get_packages(charms=parsed_args.charm, bundles=parsed_args.bundle) or None
2024-05-08 22:53:06.764   File "/snap/charmcraft/3663/lib/python3.10/site-packages/charmcraft/utils/store.py", line 27, in get_packages
2024-05-08 22:53:06.764     *(endpoints.Package(package_type="charm", package_name=charm) for charm in charms),
2024-05-08 22:53:06.764 TypeError: 'NoneType' object is not iterable
2024-05-08 22:53:06.764 Full execution log: '/home/ubuntu/.local/state/charmcraft/log/charmcraft-20240508-225306.757877.log'
```
```

**Comment by lengau** [comment]
Sorry about that! That was a bad assumption on what `argparse` would return
