### ISSUE TITLE
Charmcraft 3.x not including symlinked directories in resulting charm

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/charmcraft#1719]
### Bug Description

Building classical charms with version 3 is not adding the submodules like charmhelpers in the hooks folder.

So running a charm build with version 3 is breaking saying that it's not possible to find the module charmhelpers

### To Reproduce

install charmcraft latest/edge

build a classic charm like [charm-nrpe](https://github.com/canonical/charm-nrpe) and deploy.

### Environment

Ubuntu 22.04 LTS

### charmcraft.yaml

```shell
type: charm

parts:
  charm:
    plugin: dump
    source: .
    prime:
      - actions/*
      - files/*
      - hooks/*
      - hooks/charmhelpers/*
      - templates/*
      - actions.yaml
      - config.yaml
      - copyright
      - LICENSE
      - metadata.yaml
      - README.md
bases:
    - build-on:
        - name: ubuntu
          channel: "20.04"
          architectures: ["amd64"]
      run-on:
        - name: ubuntu
          channel: "22.04"
          architectures:
              - amd64
        - name: ubuntu
          channel: "20.04"
          architectures:
              - amd64
        - name: ubuntu
          channel: "18.04"
          architectures:
              - amd64
```

### Relevant log output

```shell
unit-nrpe-0: 12:44:22 INFO juju.worker.meterstatus skipped "meter-status-changed" hook (missing)
unit-nrpe-0: 12:44:22 WARNING unit.nrpe/0.install Traceback (most recent call last):
unit-nrpe-0: 12:44:22 WARNING unit.nrpe/0.install   File "/var/lib/juju/agents/unit-nrpe-0/charm/hooks/install", line 4, in <module>
unit-nrpe-0: 12:44:22 WARNING unit.nrpe/0.install     import services
unit-nrpe-0: 12:44:22 WARNING unit.nrpe/0.install   File "/var/lib/juju/agents/unit-nrpe-0/charm/hooks/services.py", line 11, in <module>
unit-nrpe-0: 12:44:22 WARNING unit.nrpe/0.install     from charmhelpers.core import hookenv
unit-nrpe-0: 12:44:22 WARNING unit.nrpe/0.install ModuleNotFoundError: No module named 'charmhelpers'
unit-nrpe-0: 12:44:22 ERROR juju.worker.uniter.operation hook "install" (via explicit, bespoke hook script) failed: exit status 1
unit-nrpe-0: 12:44:22 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-nrpe-0: 12:45:49 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-nrpe-0: 12:48:43 INFO juju.worker.uniter awaiting error resolution for "install" hook
```

**Comment by lengau** [comment]
Thanks for the report! 

This one was pretty interesting, as it lies in a subtle behavioural difference between `Path.rglob()` and `os.walk()` when it comes to symlinks of directories.
