### ISSUE TITLE
Charmcraft 3 does not install dependencies.

### ISSUE THREAD

**Issue by dstathis** [canonical/charmcraft#1797]
### Bug Description

When packing with charmcraft 3.x, I don't seem to have any python libraries available to my charm.

### To Reproduce

Pack a charm and deploy it.

### Environment

Charmcraft: 3.1.1
Juju: 3.5.3-genericlinux-amd64

### charmcraft.yaml

```shell
# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

type: charm
bases:
  - build-on:
    - name: "ubuntu"
      channel: "22.04"
      architectures: ["arm64"]
    run-on:
    - name: "ubuntu"
      channel: "22.04"
      architectures: ["arm64"]
  - build-on:
    - name: "ubuntu"
      channel: "20.04"
      architectures: ["arm64"]
    run-on:
    - name: "ubuntu"
      channel: "20.04"
      architectures: ["arm64"]
  - build-on:
    - name: "ubuntu"
      channel: "22.04"
      architectures: ["amd64"]
    run-on:
    - name: "ubuntu"
      channel: "22.04"
      architectures: ["amd64"]
  - build-on:
    - name: "ubuntu"
      channel: "20.04"
      architectures: ["amd64"]
    run-on:
    - name: "ubuntu"
      channel: "20.04"
      architectures: ["amd64"]
parts:
  charm:
    charm-strict-dependencies: true
    build-packages:
    - git

    # The following are needed for tls-certificates-interface
    - build-essential
    - python3-dev
    - libffi-dev
    - libssl-dev
    - pkg-config
    - rustc
    - cargo
  cos-tool:
    plugin: dump
    source: .
    build-packages:
      - curl
    override-pull: |
      curl -L -O https://github.com/canonical/cos-tool/releases/latest/download/cos-tool-${CRAFT_TARGET_ARCH}
      chmod +x cos-tool-*
```

### Relevant log output

```shell
unit-agent-17: 10:30:39 WARNING unit.agent/17.install Traceback (most recent call last):
unit-agent-17: 10:30:39 WARNING unit.agent/17.install   File "/var/lib/juju/agents/unit-agent-17/charm/./src/charm.py", line 16, in <module>
unit-agent-17: 10:30:39 WARNING unit.agent/17.install     from charms.grafana_agent.v0.cos_agent import COSAgentRequirer
unit-agent-17: 10:30:39 WARNING unit.agent/17.install   File "/var/lib/juju/agents/unit-agent-17/charm/lib/charms/grafana_agent/v0/cos_agent.py", line 217, in <module>
unit-agent-17: 10:30:39 WARNING unit.agent/17.install     from cosl import GrafanaDashboard, JujuTopology
unit-agent-17: 10:30:39 WARNING unit.agent/17.install   File "/var/lib/juju/agents/unit-agent-17/charm/venv/cosl/__init__.py", line 8, in <module>
unit-agent-17: 10:30:39 WARNING unit.agent/17.install     from .juju_topology import JujuTopology
unit-agent-17: 10:30:39 WARNING unit.agent/17.install   File "/var/lib/juju/agents/unit-agent-17/charm/venv/cosl/juju_topology.py", line 74, in <module>
unit-agent-17: 10:30:39 WARNING unit.agent/17.install     from ops.charm import CharmBase
unit-agent-17: 10:30:39 WARNING unit.agent/17.install   File "/var/lib/juju/agents/unit-agent-17/charm/venv/ops/__init__.py", line 178, in <module>
unit-agent-17: 10:30:39 WARNING unit.agent/17.install     from . import pebble  # type: ignore
unit-agent-17: 10:30:39 WARNING unit.agent/17.install   File "/var/lib/juju/agents/unit-agent-17/charm/venv/ops/pebble.py", line 68, in <module>
unit-agent-17: 10:30:39 WARNING unit.agent/17.install     import websocket  # type: ignore
unit-agent-17: 10:30:39 WARNING unit.agent/17.install ModuleNotFoundError: No module named 'websocket'
unit-agent-17: 10:30:39 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by lengau** [comment]
This is intended behaviour with `charm-strict-dependencies` - the requirements file included is expected to include the full list of packages expected in the environment as if one used `pip freeze`, `poetry export`, or similar. The 2.7 strict-deps behaviour didn't do this and was considered a bug. See https://github.com/canonical/charmcraft/issues/1473 for more discussion.
