### ISSUE TITLE
KeyError: 'getpwuid(): uid not found

### ISSUE THREAD

**Issue by erik78se** [canonical/charmcraft#199]
When trying to create a new charm (operator).... it fails.

* I have a sssd / Active Directory / LDAP environment.
* I'm trying to create a new charm with charmcraft. This fails.

$ charmcraft init 
charmcraft internal error! KeyError: 'getpwuid(): uid not found: 12345' (full execution logs in /home/sssler/snap/charmcraft/common/charmcraft-log-vpjqqr9s)

$ cat charmcraft-log-vpjqqr9s
2020-11-16 16:31:00,252  charmcraft.guard               DEBUG    Starting charmcraft version 0.6.0+17.gc56c4d7
2020-11-16 16:31:00,252  charmcraft.main                DEBUG    Raw pre-parsed sysargs: flags={'help': False, 'verbose': False, 'quiet': False} filtered=['init']
2020-11-16 16:31:00,252  charmcraft.main                DEBUG    General parsed sysargs: command='init' args=[]
2020-11-16 16:31:00,253  charmcraft.commands.init       DEBUG    Using existing project directory '/home/sssler/allcode/charm-atsrti/rti-runner'
2020-11-16 16:31:00,254  charmcraft                     ERROR    charmcraft internal error! KeyError: 'getpwuid(): uid not found: 3787' (full execution logs in /home/sssler/snap/charmcraft/common/charmcraft-log-vpjqqr9s)
2020-11-16 16:31:00,254  charmcraft.guard               ERROR    
Traceback (most recent call last):
  File "/snap/charmcraft/165/lib/charmcraft/main.py", line 256, in main
    dispatcher.run()
  File "/snap/charmcraft/165/lib/charmcraft/main.py", line 243, in run
    self.command.run(self.parsed_args)
  File "/snap/charmcraft/165/lib/charmcraft/commands/init.py", line 91, in run
    gecos = pwd.getpwuid(os.getuid()).pw_gecos.split(',', 1)[0]
KeyError: 'getpwuid(): uid not found: 12345'

$ id
uid=12345(sssler) gid=1000(sdtt) groups=1000(sdtt) ....

== charmcraft snap ==
charmcraft         0.6.0+17.gc56c4d7     165    latest/edge    chipaca             -

=== Ubuntu ==
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"

=== uname ===
 uname -a
Linux dcv-engineering 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by facundobatista** [comment]
This will solved automatically when we drop the snap strict confinement.

**Comment by facundobatista** [comment]
Now `charmcraft` uses the "classic" mode (currently released to `edge`). Would you please try if that solved your issue?

Thanks!

**Comment by facundobatista** [comment]
Fixed in #369
