### ISSUE TITLE
Initial tests from `charmcraft init` do not pass

### ISSUE THREAD

**Issue by tomwardill** [canonical/charmcraft#243]
If you create a new charm with `charmcraft init`, the tests will not pass out of the box.

This appears to be because the `config.yaml` file exists, but does not contain any valid yaml (just comments).

```
tomwardill@microk8s-juju:~/work/harbor-charms/harbor-core$ ./run_tests 
test_action (tests.test_charm.TestCharm) ... ERROR
test_action_fail (tests.test_charm.TestCharm) ... ERROR
test_config_changed (tests.test_charm.TestCharm) ... ERROR

======================================================================
ERROR: test_action (tests.test_charm.TestCharm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tomwardill/work/harbor-charms/harbor-core/tests/test_charm.py", line 21, in test_action
    harness = Harness(HarborCoreCharm)
  File "/home/tomwardill/work/harbor-charms/harbor-core/venv/lib/python3.8/site-packages/ops/testing.py", line 92, in __init__
    self._update_config(key_values=self._load_config_defaults(config))
  File "/home/tomwardill/work/harbor-charms/harbor-core/venv/lib/python3.8/site-packages/ops/testing.py", line 277, in _load_config_defaults
    charm_config = charm_config.get('options', {})
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: test_action_fail (tests.test_charm.TestCharm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tomwardill/work/harbor-charms/harbor-core/tests/test_charm.py", line 30, in test_action_fail
    harness = Harness(HarborCoreCharm)
  File "/home/tomwardill/work/harbor-charms/harbor-core/venv/lib/python3.8/site-packages/ops/testing.py", line 92, in __init__
    self._update_config(key_values=self._load_config_defaults(config))
  File "/home/tomwardill/work/harbor-charms/harbor-core/venv/lib/python3.8/site-packages/ops/testing.py", line 277, in _load_config_defaults
    charm_config = charm_config.get('options', {})
AttributeError: 'NoneType' object has no attribute 'get'

======================================================================
ERROR: test_config_changed (tests.test_charm.TestCharm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tomwardill/work/harbor-charms/harbor-core/tests/test_charm.py", line 13, in test_config_changed
    harness = Harness(HarborCoreCharm)
  File "/home/tomwardill/work/harbor-charms/harbor-core/venv/lib/python3.8/site-packages/ops/testing.py", line 92, in __init__
    self._update_config(key_values=self._load_config_defaults(config))
  File "/home/tomwardill/work/harbor-charms/harbor-core/venv/lib/python3.8/site-packages/ops/testing.py", line 277, in _load_config_defaults
    charm_config = charm_config.get('options', {})
AttributeError: 'NoneType' object has no attribute 'get'

----------------------------------------------------------------------
Ran 3 tests in 0.017s

FAILED (errors=3)

```

Either removing `config.yaml` so it drops into the default in `_load_config_defaults`, or making it's contents represent an empty dictionary is enough to fix it.

**Comment by facundobatista** [comment]
Just wrote #247 about the future of `init` tests, which will fix this.
