### ISSUE TITLE
debian not supported in manifest.yaml

### ISSUE THREAD

**Issue by endikap100** [canonical/charmcraft#321]
building a charm in debian creates a architectures which it's not supported in juju, it only supports ubuntu at this moment.

see the discusion on mattermost:
https://chat.charmhub.io/charmhub/pl/cqydkpb5p3dybgmzk1xnqyu1kc

manifest.yaml created building the charm in debian:
```
bases:
- architectures:
  - amd64
  channel: 5.10.0-6-amd64
  name: debian
charmcraft-started-at: '2021-04-27T10:44:52.408391Z'
charmcraft-version: 0.10.0
```

**Comment by sergiusens** [comment]
Once the bases definition in charmcraft.yaml work finalizes the rules of where to build for what target will result in a clearer experience wrt expectations.

**Comment by endikap100** [comment]
ok, and can I do something to be able to build it from debian?
I have tried creating a manifest.yaml with the following content
```
bases:
- architectures:
  - amd64
  channel: '20.04'
  name: ubuntu
charmcraft-started-at: '2021-04-27T13:13:55.050903Z'
charmcraft-version: 0.10.0
```

and it fails to build with this error
```
2021-04-29 12:26:07,354  charmcraft                     ERROR    charmcraft internal error! FileExistsError: [Errno 17] File exists: '/home/endika/git/knf_poc/test/charms/man/manifest.yaml' -> '/home/endika/git/knf_poc/test/charms/man/build/manifest.yaml' (full execution logs in /tmp/charmcraft-log-h77eq5tp)
2021-04-29 12:26:07,355  charmcraft.guard               ERROR    
Traceback (most recent call last):
  File "/home/endika/.local/lib/python3.9/site-packages/charmcraft/main.py", line 305, in main
    dispatcher.run()
  File "/home/endika/.local/lib/python3.9/site-packages/charmcraft/main.py", line 292, in run
    self.command.run(self.parsed_args)
  File "/home/endika/.local/lib/python3.9/site-packages/charmcraft/commands/build.py", line 401, in run
    builder.run()
  File "/home/endika/.local/lib/python3.9/site-packages/charmcraft/commands/build.py", line 112, in run
    linked_entrypoint = self.handle_generic_paths()
  File "/home/endika/.local/lib/python3.9/site-packages/charmcraft/commands/build.py", line 190, in handle_generic_paths
    os.link(str(abs_path), str(dest_path))
FileExistsError: [Errno 17] File exists: '/home/endika/git/knf_poc/test/charms/man/manifest.yaml' -> '/home/endika/git/knf_poc/test/charms/man/build/manifest.yaml'
```

**Comment by facundobatista** [comment]
Hello!

All is currently in place today to build in a debian host but producing a charm for platforms suitable for Juju. 

Note that the configuration information for this should go in a file named `charmcraft.yaml`, not a manifest one. Check the [general configuration documentation](https://juju.is/docs/sdk/charmcraft-config) and [this tutorial on using different bases and providers](https://discourse.charmhub.io/t/charmcraft-bases-provider-support/4713). 

Thanks!
