### ISSUE TITLE
`charmcraft build` breaks when pip packages come from github

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#55]
`charmcraft build` errors when pip packages located in github are included in the requirements.txt. 

This issue can be reproduced if you build a charm where the requirements.txt contains pip packages that live in github.

Reproducer:
```
git clone https://github.com/ducks23/charm-slurmdbd -b bdx_charmcraft

cd charm-slurmdbd

charmcraft build
```

Here is our example of the breakage below:

```
$ cat requirements.txt
ops
#git+https://github.com/omnivector-solutions/interface-mysql.git@master
#git+https://github.com/omnivector-solutions/slurm-snap-manager.git@master

$ charmcraft build
Done, charm left in 'slurmdbd.charm'

$ vim requirements.txt

$ cat requirements.txt
ops
git+https://github.com/omnivector-solutions/interface-mysql.git@master
git+https://github.com/omnivector-solutions/slurm-snap-manager.git@master

$ charmcraft build
Executing ['pip3', 'install', '--target=/home/bdx/allcode/github/ducks23/charm-slurmdbd/build/venv', '--requirement=/home/bdx/allcode/github/ducks23/charm-slurmdbd/requirements.txt'] failed with return code 1
problems installing dependencies
```
I can install the requirements.txt by hand successfully
```
$ pip install -r requirements.txt
Collecting git+https://github.com/omnivector-solutions/interface-mysql.git@master (from -r requirements.txt (line 2))
  Cloning https://github.com/omnivector-solutions/interface-mysql.git (to revision master) to /tmp/pip-req-build-ztlxwhvf
  Running command git clone -q https://github.com/omnivector-solutions/interface-mysql.git /tmp/pip-req-build-ztlxwhvf
Collecting git+https://github.com/omnivector-solutions/slurm-snap-manager.git@master (from -r requirements.txt (line 3))
  Cloning https://github.com/omnivector-solutions/slurm-snap-manager.git (to revision master) to /tmp/pip-req-build-pwosnebt
  Running command git clone -q https://github.com/omnivector-solutions/slurm-snap-manager.git /tmp/pip-req-build-pwosnebt
Requirement already satisfied: ops in /home/bdx/allcode/github/venv/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.6.1)
Requirement already satisfied: PyYAML in /home/bdx/allcode/github/venv/lib/python3.8/site-packages (from ops->-r requirements.txt (line 1)) (5.3.1)
Building wheels for collected packages: interface-mysql, slurm-snap-manager
  Building wheel for interface-mysql (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/bdx/allcode/github/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ztlxwhvf/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ztlxwhvf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-y8jlp8ro
       cwd: /tmp/pip-req-build-ztlxwhvf/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for interface-mysql
  Running setup.py clean for interface-mysql
  Building wheel for slurm-snap-manager (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/bdx/allcode/github/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-pwosnebt/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-pwosnebt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-gd2m4kjg
       cwd: /tmp/pip-req-build-pwosnebt/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for slurm-snap-manager
  Running setup.py clean for slurm-snap-manager
Failed to build interface-mysql slurm-snap-manager
Installing collected packages: interface-mysql, slurm-snap-manager
    Running setup.py install for interface-mysql ... done
    Running setup.py install for slurm-snap-manager ... done
Successfully installed interface-mysql-0.0.1 slurm-snap-manager-0.0.1
```

Running `snappy-debug` shows:

```
= AppArmor =
Time: Jun 24 10:26:01
Log: apparmor="DENIED" operation="open" profile="snap.charmcraft.charmcraft" name="/etc/" pid=3626019 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /etc/ (read)
Suggestions:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
* adjust snap to use snap layouts (https://forum.snapcraft.io/t/snap-layouts/7207)

= AppArmor =
Time: Jun 24 10:28:39
```

**Comment by facundobatista** [comment]
Hello @jamesbeedy! Thanks for your time helping us to improve charmcraft.

Would you please retry the build but in verbose mode and then provide us the whole log? It would be: `charmcraft --verbose build`

Thanks!!!

**Comment by ducks23** [comment]
@facundobatista 
just ran that
```
charm-slurmdbd$ charmcraft --verbose build
2020-06-24 19:39:44,847  charmcraft.commands.build DEBUG    working arguments: {'from': PosixPath('/home/jesse/slurm/charm-slurmdbd'), 'entrypoint': PosixPath('/home/jesse/slurm/charm-slurmdbd/src/charm.py'), 'requirement': [PosixPath('/home/jesse/slurm/charm-slurmdbd/requirements.txt')]}
2020-06-24 19:39:44,847  charmcraft.commands.build DEBUG    Building charm in '/home/jesse/slurm/charm-slurmdbd/build'
2020-06-24 19:39:44,848  charmcraft.commands.build DEBUG    Linking in basic files and charm code
2020-06-24 19:39:44,848  charmcraft.commands.build DEBUG    Creating the dispatch mechanism
2020-06-24 19:39:44,848  charmcraft.commands.build DEBUG    Including current 'start' hook
2020-06-24 19:39:44,848  charmcraft.commands.build DEBUG    Including current 'db-relation-changed' hook
2020-06-24 19:39:44,848  charmcraft.commands.build DEBUG    Including current 'munge-relation-changed' hook
2020-06-24 19:39:44,849  charmcraft.commands.build DEBUG    Including current 'install' hook
2020-06-24 19:39:44,849  charmcraft.commands.build DEBUG    Creating the 'upgrade-charm' hook script pointing to dispatch
2020-06-24 19:39:44,849  charmcraft.commands.build DEBUG    Installing dependencies
2020-06-24 19:39:45,997  charmcraft.commands.build DEBUG    :: Collecting git+https://github.com/omnivector-solutions/interface-munge.git@master (from -r /home/jesse/slurm/charm-slurmdbd/requirements.txt (line 2))
2020-06-24 19:39:45,997  charmcraft.commands.build DEBUG    ::   Cloning https://github.com/omnivector-solutions/interface-munge.git (to master) to /tmp/pip-uqhbp3tp-build
2020-06-24 19:39:46,953  charmcraft.commands.build DEBUG    :: Collecting git+https://github.com/omnivector-solutions/ops-interface-host-port.git@master (from -r /home/jesse/slurm/charm-slurmdbd/requirements.txt (line 3))
2020-06-24 19:39:46,953  charmcraft.commands.build DEBUG    ::   Cloning https://github.com/omnivector-solutions/ops-interface-host-port.git (to master) to /tmp/pip-n3c3b_s0-build
2020-06-24 19:39:47,966  charmcraft.commands.build DEBUG    :: Collecting git+https://github.com/omnivector-solutions/slurm-snap-manager.git@master (from -r /home/jesse/slurm/charm-slurmdbd/requirements.txt (line 4))
2020-06-24 19:39:47,966  charmcraft.commands.build DEBUG    ::   Cloning https://github.com/omnivector-solutions/slurm-snap-manager.git (to master) to /tmp/pip-0oa9vidf-build
2020-06-24 19:39:48,866  charmcraft.commands.build DEBUG    :: Collecting ops (from -r /home/jesse/slurm/charm-slurmdbd/requirements.txt (line 1))
2020-06-24 19:39:49,883  charmcraft.commands.build DEBUG    ::   Using cached https://files.pythonhosted.org/packages/25/0b/0ef869533f1615403d1940ae1a5a27343667ce64a807da05f42d8e50f6d4/ops-0.6.1-py3-none-any.whl
2020-06-24 19:39:49,888  charmcraft.commands.build DEBUG    :: Collecting PyYAML (from ops->-r /home/jesse/slurm/charm-slurmdbd/requirements.txt (line 1))
2020-06-24 19:39:50,183  charmcraft.commands.build DEBUG    :: Installing collected packages: PyYAML, ops, interface-munge-jesseleo, interface-host-port, slurm-snap-manager
2020-06-24 19:39:50,224  charmcraft.commands.build DEBUG    :: Exception:
2020-06-24 19:39:50,224  charmcraft.commands.build DEBUG    :: Traceback (most recent call last):
2020-06-24 19:39:50,224  charmcraft.commands.build DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
2020-06-24 19:39:50,224  charmcraft.commands.build DEBUG    ::     status = self.run(options, args)
2020-06-24 19:39:50,224  charmcraft.commands.build DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
2020-06-24 19:39:50,224  charmcraft.commands.build DEBUG    ::     prefix=options.prefix_path,
2020-06-24 19:39:50,224  charmcraft.commands.build DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
2020-06-24 19:39:50,224  charmcraft.commands.build DEBUG    ::     **kwargs
2020-06-24 19:39:50,224  charmcraft.commands.build DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
2020-06-24 19:39:50,224  charmcraft.commands.build DEBUG    ::     self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
2020-06-24 19:39:50,225  charmcraft.commands.build DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
2020-06-24 19:39:50,225  charmcraft.commands.build DEBUG    ::     isolated=self.isolated,
2020-06-24 19:39:50,225  charmcraft.commands.build DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
2020-06-24 19:39:50,225  charmcraft.commands.build DEBUG    ::     prefix=prefix,
2020-06-24 19:39:50,225  charmcraft.commands.build DEBUG    ::   File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
2020-06-24 19:39:50,225  charmcraft.commands.build DEBUG    ::     i.finalize_options()
2020-06-24 19:39:50,225  charmcraft.commands.build DEBUG    ::   File "/usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl/setuptools/command/install.py", line 38, in finalize_options
2020-06-24 19:39:50,225  charmcraft.commands.build DEBUG    ::     orig.install.finalize_options(self)
2020-06-24 19:39:50,225  charmcraft.commands.build DEBUG    ::   File "/usr/lib/python3.6/distutils/command/install.py", line 274, in finalize_options
2020-06-24 19:39:50,225  charmcraft.commands.build DEBUG    ::     raise DistutilsOptionError("can't combine user with prefix, "
2020-06-24 19:39:50,225  charmcraft.commands.build DEBUG    :: distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
2020-06-24 19:39:50,286  charmcraft.commands.build ERROR    Executing ['pip3', 'install', '--target=/home/jesse/slurm/charm-slurmdbd/build/venv', '--requirement=/home/jesse/slurm/charm-slurmdbd/requirements.txt'] failed with return code 2
2020-06-24 19:39:50,287  charmcraft.main    ERROR    problems installing dependencies
```

**Comment by chipaca** [comment]
This is running `charmcraft` from the snap, then. It doesn't currently ship `git` (nor `bzr` :slightly_smiling_face:) so it can't do much there. However the error seems to point to something else, which is strange.
Just to make sure, could you create a virtualenv, `pip install charmcraft` in it, and run *that* charmcraft build?

**Comment by jamesbeedy** [comment]
@chipaca `charmcraft` installed from pypi succeeds

**Comment by chipaca** [comment]
so despite the weird error, it likely is the lack of `git` in the snap that trips it up. Good to know :-) thanks

I've already [kicked off](https://forum.snapcraft.io/t/request-for-connection-for-charmcraft/18459?u=chipaca) the process to get git running happily inside the snap but it might take a bit.

**Comment by chipaca** [comment]
@jamesbeedy could you try the 0.2 snap? I've added preliminary git support to it. It might work :-)
it fails to work with some submodules, apparently in some situations git will try to use ssh and I thought that was just too far. But http git works fine, tested against both github and launchpad with (and without) https submodules.

**Comment by jamesbeedy** [comment]
@chipaca works for me too. Thanks!

**Comment by jamesbeedy** [comment]
`charmcraft build` now prompting for github user/pass
```
$ charmcraft build
Username for 'https://github.com':
```
