### ISSUE TITLE
Issues with concurrent builds

### ISSUE THREAD

**Issue by johnsca** [canonical/charmcraft#554]
I am working on a test in [metallb-operator](https://github.com/charmed-kubernetes/metallb-operator) and was trying to build the two charms for that in parallel. It worked fine for me locally, but on the GitHub runner (a fresh VM, with a fresh install of both lxd and charmcraft on the default channel / track), I ran into a few errors that appear to be due to race conditions in setting up LXD for the builder.

The first one I [ran into](https://github.com/charmed-kubernetes/metallb-operator/pull/18/checks?check_run_id=3693265761#step:6:58) (NB: these build log links will eventually expire) was:

```
Packing charm 'metallb-speaker_ubuntu-20.04-amd64.charm'...
charmcraft internal error! LXDError: Failed to add remote 'craft-com.ubuntu.cloud-buildd'.
* Command that failed: 'lxc remote add craft-com.ubuntu.cloud-buildd https://cloud-images.ubuntu.com/buildd/releases --protocol=simplestreams'
* Command exit code: 1
* Command standard error output: b'Error: Remote craft-com.ubuntu.cloud-buildd exists as <https://cloud-images.ubuntu.com/buildd/releases>\n' (full execution logs in /home/runner/snap/charmcraft/common/charmcraft-log-osa2otki)
```

I tried working around that by running that `lxc` command manually earlier in the Workflow, but then I [ran into](https://github.com/charmed-kubernetes/metallb-operator/pull/18/checks?check_run_id=3700739113#step:7:58):

```
Packing charm 'metallb-controller_ubuntu-20.04-amd64.charm'...
charmcraft internal error! LXDError: Failed to create project 'charmcraft'.
* Command that failed: 'lxc --project charmcraft project create local:charmcraft'
* Command exit code: 1
* Command standard error output: b'Error: Failed creating project "charmcraft": Failed adding database record: This project already exists\n' (full execution logs in /home/runner/snap/charmcraft/common/charmcraft-log-4l5wgu0x)
```

Once again, I added the `lxc` command to the Workflow before the build, and then I [ran into](https://github.com/charmed-kubernetes/metallb-operator/pull/18/checks?check_run_id=3700929568#step:7:59):

```
Packing charm 'metallb-controller_ubuntu-20.04-amd64.charm'...
charmcraft internal error! LXDError: Failed to launch instance 'charmcraft-metallb-controller-1058053-0-0-amd64'.
* Command that failed: "lxc --project charmcraft launch craft-com.ubuntu.cloud-buildd:20.04 local:charmcraft-metallb-controller-1058053-0-0-amd64 --config 'raw.idmap=both 1001 0' --config security.syscalls.intercept.mknod=true"
* Command exit code: 1
* Command output: b'Creating charmcraft-metallb-controller-1058053-0-0-amd64\n'
* Command standard error output: b'Error: Failed instance creation: Failed creating instance record: Failed initialising instance: Invalid devices: Failed detecting root disk device: No root device could be found\n' (full execution logs in /home/runner/snap/charmcraft/common/charmcraft-log-jsos__q1)
```

That one has me stumped so I ended up just de-parallelizing the builds and that works, but it is slower and the errors were confusing and not immediately obvious that they were due to the concurrent build conflict.

**Comment by gruyaume** [comment]
I'm getting the same issue here when I try to parallelize builds leveraging pytest_operator's OpsTest plugin. 

```
from pytest_operator.plugin import OpsTest

    async def build_charm(charm_name: str):
        charm_directory = await asyncio.create_task(ops_test.build_charm(f"../{charm_name}"))
        os.rename(charm_directory, f"../{charm_name}/{charm_name}.charm")
        return charm_directory
```

The error I'm getting:
```
Traceback (most recent call last):
  File "/home/runner/work/magma-orc8r-dev/magma-orc8r-dev/integration_tests/integration_tests.py", line 51, in test_build_and_deploy
    await asyncio.gather(*coros)
  File "/home/runner/work/magma-orc8r-dev/magma-orc8r-dev/integration_tests/integration_tests.py", line 46, in build_charm
    charm_directory = await asyncio.create_task(ops_test.build_charm(f"../{charm_name}"))
  File "/home/runner/work/magma-orc8r-dev/magma-orc8r-dev/integration_tests/.tox/integration/lib/python3.8/site-packages/pytest_operator/plugin.py", line 340, in build_charm
    raise RuntimeError(
RuntimeError: Failed to build charm ../fluentd-elasticsearch:
Packing charm 'fluentd-elasticsearch_ubuntu-20.04-amd64.charm'...
charmcraft internal error! LXDError: Failed to add remote 'craft-com.ubuntu.cloud-buildd'.
* Command that failed: 'lxc remote add craft-com.ubuntu.cloud-buildd https://cloud-images.ubuntu.com/buildd/releases --protocol=simplestreams'
* Command exit code: 1
* Command standard error output: b'Error: Remote craft-com.ubuntu.cloud-buildd exists as <https://cloud-images.ubuntu.com/buildd/releases>\n' (full execution logs in /home/runner/snap/charmcraft/common/charmcraft-log-l_ofyiqr)
* ```

**Comment by facundobatista** [comment]
It's a good idea. We need [support in Craft Providers for this](https://github.com/canonical/craft-providers/issues/96).

**Comment by ca-scribner** [comment]
While this is still open, a fix we've used in other repos is to build with `--destructive-mode`, which avoids LXC entirely (if I understand correctly)

**Comment by facundobatista** [comment]
The fix is now included in Charmcraft.
