### ISSUE TITLE
charmcraft 1.2.1 fails to copy config.yaml

### ISSUE THREAD

**Issue by sed-i** [canonical/charmcraft#572]
I am trying to pack [jellyfin-operator](https://github.com/sed-i/jellyfin-operator) and charmcraft fails to copy `config.yaml`:

```
> charmcraft version
1.2.1

> charmcraft clean
Cleaned project 'jellyfin-k8s'.

> charmcraft pack
Packing charm 'jellyfin-k8s_ubuntu-20.04-amd64.charm'...
Parts processing error: Failed to copy '/root/project/build/stage/config.yaml': no such file or directory. (full execution logs in '/tmp/charmcraft.log')
Failed to build charm for bases index '0'. (full execution logs in '/home/tux/snap/charmcraft/common/charmcraft-log-v7i73tb0')
```

But if I get `config.yaml` out of the way, packing works:

```
> mv config.yaml config.yaml.hid
> charmcraft pack
Packing charm 'jellyfin-k8s_ubuntu-20.04-amd64.charm'...
Created 'jellyfin-k8s_ubuntu-20.04-amd64.charm'.
```
[cc121.log](https://github.com/canonical/charmcraft/files/7343274/cc121.log)

**Comment by sed-i** [comment]
With charmcraft 1.3.1 there's a different error: pip fails collecting `tomli`:
```
> sudo snap refresh charmcraft --channel=latest/candidate
charmcraft (candidate) 1.3.1 from Canonical✓ refreshed

> charmcraft version
1.3.1
 
> charmcraft clean
Cleaned project 'jellyfin-k8s'.

> charmcraft pack
Packing charm 'jellyfin-k8s_ubuntu-20.04-amd64.charm'...
Parts processing error: Failed to run the build script for part 'charm'. (full execution logs in '/tmp/charmcraft.log')
Failed to build charm for bases index '0'. (full execution logs in '/home/tux/snap/charmcraft/common/charmcraft-log-do0xa77p')
```
```
       Collecting tomli
         Using cached tomli-1.2.1.tar.gz (14 kB)
       ERROR: Exception:
       Traceback (most recent call last):
         File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
           status = self.run(options, args)
         File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 357, in run
           resolver.resolve(requirement_set)
         File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
           discovered_reqs.extend(self._resolve_one(requirement_set, req))
         File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
           abstract_dist = self._get_abstract_dist_for(req_to_install)
         File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
           abstract_dist = self.preparer.prepare_linked_requirement(req)
         File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 515, in prepare_linked_requirement
           abstract_dist = _get_prepared_distribution(
         File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 94, in _get_prepared_distribution
           with req_tracker.track(req):
         File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
           return next(self.gen)
         File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip/_internal/req/req_tracker.py", line 148, in track
           self.add(req)
         File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip/_internal/req/req_tracker.py", line 115, in add
           raise LookupError(message)
       LookupError: https://files.pythonhosted.org/packages/75/50/973397c5ba854445bcc396b593b5db1958da6ab8d665b27397daa1497018/tomli-1.2.1.tar.gz#sha256=a5b75cb6f3968abb47af1b40c1819dc519ea82bcc065776a866e8d74c5ca9442 (from https://pypi.org/simple/tomli/) (requires-python:>=3.6) is already being built: tomli>=1.0 from https://files.pythonhosted.org/packages/75/50/973397c5ba854445bcc396b593b5db1958da6ab8d665b27397daa1497018/tomli-1.2.1.tar.gz#sha256=a5b75cb6f3968abb47af1b40c1819dc519ea82bcc065776a866e8d74c5ca9442
       ----------------------------------------
     ERROR: Command errored out with exit status 2: /root/parts/charm/build/staging-venv/bin/python3 /root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-wpek3mc0/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'flit_core>=3.2.0,<4' Check the logs for full command output.
     ----------------------------------------
   ERROR: Command errored out with exit status 1: /root/parts/charm/build/staging-venv/bin/python3 /root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-75sarsus/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45' wheel 'tomli>=1.0' 'packaging>=20.0' Check the logs for full command output.
   ----------------------------------------
 ERROR: Command errored out with exit status 1: /root/parts/charm/build/staging-venv/bin/python3 /root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-4ef_do63/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools; python_version != '"'"'3.3'"'"'' 'setuptools<40.0; python_version == '"'"'3.3'"'"'' wheel setuptools_scm Check the logs for full command output.
```

[cc131.log](https://github.com/canonical/charmcraft/files/7343326/cc131.log)
