### ISSUE TITLE
Charmcraft fails to build due to lack of Git

### ISSUE THREAD

**Issue by Artonus** [canonical/charmcraft#605]
Hi there!
I have found an issue in which charmcraft fails to pack the operator when the package specification in the `requirements.txt` contains the reference to the git repository in example:
` git+https://github.com/canonical/operator/#egg=ops`

Lxd version : `4.0.8`
Charmcraft version: `1.2.1`

My `charmcraft.yaml` file has the following contents:

```
# Learn more about charmcraft.yaml configuration at:
# https://juju.is/docs/sdk/charmcraft-config
type: "charm"
bases:
  - build-on:
    - name: "ubuntu"
      channel: "20.04"
    run-on:
    - name: "ubuntu"
      channel: "20.04"
```

The error logs are following:
```
 2021-11-19 14:20:56,206  craft_parts.executor.step_handler        DEBUG    :: Creating the 'install' hook script pointing to dispatch
mm 2021-11-19 14:20:56,206  craft_parts.executor.step_handler        DEBUG    :: Creating the 'start' hook script pointing to dispatch
mm 2021-11-19 14:20:56,206  craft_parts.executor.step_handler        DEBUG    :: Creating the 'upgrade-charm' hook script pointing to dispatch
mm 2021-11-19 14:20:56,206  craft_parts.executor.step_handler        DEBUG    :: Installing dependencies
mm 2021-11-19 14:20:56,206  craft_parts.executor.step_handler        DEBUG    :: Running external command ['pip3', '--version']
mm 2021-11-19 14:20:56,680  craft_parts.executor.step_handler        DEBUG    :: :: pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
mm 2021-11-19 14:20:56,710  craft_parts.executor.step_handler        DEBUG    :: Running external command ['pip3', 'install', '--target=/root/project/build/parts/charm/install/venv', '--requirement=requirements.txt']
mm 2021-11-19 14:20:57,355  craft_parts.executor.step_handler        DEBUG    :: :: Collecting ops
mm 2021-11-19 14:20:57,355  craft_parts.executor.step_handler        DEBUG    :: ::   Cloning https://github.com/canonical/operator/ to /tmp/pip-install-8zar0ant/ops
mm 2021-11-19 14:20:57,355  craft_parts.executor.step_handler        DEBUG    :: ::   Running command git clone -q https://github.com/canonical/operator/ /tmp/pip-install-8zar0ant/ops
mm 2021-11-19 14:20:57,356  craft_parts.executor.step_handler        DEBUG    :: ::   ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/canonical/operator/ /tmp/pip-install-8zar0ant/ops
mm 2021-11-19 14:20:57,356  craft_parts.executor.step_handler        DEBUG    :: :: ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
mm 2021-11-19 14:20:57,384  craft_parts.executor.step_handler        DEBUG    :: Executing ['pip3', 'install', '--target=/root/project/build/parts/charm/install/venv', '--requirement=requirements.txt'] failed with return code 1
mm 2021-11-19 14:20:57,384  craft_parts.executor.step_handler        DEBUG    :: Traceback (most recent call last):
mm 2021-11-19 14:20:57,385  craft_parts.executor.step_handler        DEBUG    :: File "/snap/charmcraft/x2/lib/charmcraft/charm_builder.py", line 334, in <module>
mm 2021-11-19 14:20:57,385  craft_parts.executor.step_handler        DEBUG    :: main()
mm 2021-11-19 14:20:57,385  craft_parts.executor.step_handler        DEBUG    :: File "/snap/charmcraft/x2/lib/charmcraft/charm_builder.py", line 330, in main
mm 2021-11-19 14:20:57,385  craft_parts.executor.step_handler        DEBUG    :: builder.build_charm()
mm 2021-11-19 14:20:57,385  craft_parts.executor.step_handler        DEBUG    :: File "/snap/charmcraft/x2/lib/charmcraft/charm_builder.py", line 90, in build_charm
mm 2021-11-19 14:20:57,385  craft_parts.executor.step_handler        DEBUG    :: self.handle_dependencies()
mm 2021-11-19 14:20:57,385  craft_parts.executor.step_handler        DEBUG    :: File "/snap/charmcraft/x2/lib/charmcraft/charm_builder.py", line 244, in handle_dependencies
mm 2021-11-19 14:20:57,385  craft_parts.executor.step_handler        DEBUG    :: raise CommandError("problems installing dependencies")
mm 2021-11-19 14:20:57,385  craft_parts.executor.step_handler        DEBUG    :: charmcraft.cmdbase.CommandError: problems installing dependencies
mm 2021-11-19 14:20:57,405  charmcraft                               ERROR    Parts processing error: Failed to run the build script for part 'charm'. (full execution logs in '/tmp/charmcraft.log')

2021-11-19 14:20:57,575  craft_providers.lxd.lxc                  DEBUG    Executing on host: lxc --project charmcraft config device show local:charmcraft-mc-operator-1839996-0-0-amd64
2021-11-19 14:20:57,618  craft_providers.lxd.lxc                  DEBUG    Executing on host: lxc --project charmcraft config device remove local:charmcraft-mc-operator-1839996-0-0-amd64 disk-/root/project
2021-11-19 14:20:57,686  craft_providers.lxd.lxc                  DEBUG    Executing on host: lxc --project charmcraft stop local:charmcraft-mc-operator-1839996-0-0-amd64
2021-11-19 14:20:58,713  charmcraft                               ERROR    Failed to build charm for bases index '0'. (full execution logs in '/home/bartek/snap/charmcraft/common/charmcraft-log-2asxqh4w')
```

When I specify the ops module using the standard notation `ops >= 1.2.0` everything works well.

Is there any reason that the Git is not installed on the build machine?

Thanks a lot!

**Comment by Artonus** [comment]
Managed to find the solution for this:

Putting the following code in the `charmcraft.yaml` file has solved the issue.
```
parts:
  charm:
    build-packages:
      - git
```
