### ISSUE TITLE
Can't pip install charmcraft on latest Ubuntu

### ISSUE THREAD

**Issue by AurelienLourot** [canonical/charmcraft#615]
As mentioned in https://github.com/canonical/charmcraft/pull/487#issuecomment-894529408 , trying to pull any version of charmcraft newer than 1.0.0 with pip on Ubuntu series newer than Focal will fail with

```
Collecting python-apt
  Using cached python-apt-0.7.8.tar.bz2 (49 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bpzx9t64/python-apt_dae4b8816222415991bfc123d7d1dab9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bpzx9t64/python-apt_dae4b8816222415991bfc123d7d1dab9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qulkv83y
         cwd: /tmp/pip-install-bpzx9t64/python-apt_dae4b8816222415991bfc123d7d1dab9/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bpzx9t64/python-apt_dae4b8816222415991bfc123d7d1dab9/setup.py", line 6, in <module>
        from DistUtilsExtra.command import *
    ModuleNotFoundError: No module named 'DistUtilsExtra'
```

The solution would be to install a much newer version of `python-apt` on your system with `sudo apt install python-apt`, however this is not possible anymore on Ubuntu series newer than Focal: there only `python3-apt` can be apt-installed, and it doesn't get picked up because charmcraft has a dependency to `python-apt`, not `python3-apt`.

The only workaround I found so far is to also `pip install` the latest `python-apt` by adding this to my `build-requirements.txt`:

```
git+https://salsa.debian.org/apt-team/python-apt.git#egg=python-apt
```

**Comment by heitorPB** [comment]
It would be awesome if there was a .deb to install charmcraft.

**Comment by heitorPB** [comment]
Installing from PyPI works, but charmcraft does not:

```bash
$ charmcraft pack
Traceback (most recent call last):
  File "/home/h/.local/bin/charmcraft", line 5, in <module>
    from charmcraft.main import main
  File "/home/h/.local/lib/python3.8/site-packages/charmcraft/main.py", line 24, in <module>
    from craft_cli import emit, EmitterMode, CraftError
ModuleNotFoundError: No module named 'craft_cli'
```
