### ISSUE TITLE
v1.4.0 - failing to login and use anything related to credentials

### ISSUE THREAD

**Issue by EMCP** [canonical/charmcraft#631]
I somehow got this candidate release on Ubuntu 20.04 LTS .. will likely look to revert to stable but.. seems I login but nothing works

```
$ charmcraft login
Opening an authorization web page in your browser.
If it does not open, please open this URL:
 https://api.jujucharms.com/identity/login?did=9149c5blahlblahblah

Logged in as 'MYUSER'.                                                                                                                                 

$ charmcraft status MYCHARM
Not logged in.                                                                                                                                       
Full execution log: '/home/MYUSER/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220122-170629.358793.log'                                   

$ cat /home/MYUSER/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220122-170629.358793.log 
2022-01-22 17:06:29.359 Starting charmcraft version 1.4.0
2022-01-22 17:06:29.359 Raw pre-parsed sysargs: args={'help': False, 'verbose': False, 'quiet': False, 'trace': False, 'project_dir': None} filtered=['status', 'MYCHARM']
2022-01-22 17:06:29.359 General parsed sysargs: command='status' args=['MYCHARM']
2022-01-22 17:06:29.359 Couldn't find config file '/home/MYUSER/Dev/git/scharms/MYCHARM/charmcraft.yaml'
2022-01-22 17:06:29.359 Command parsed sysargs: Namespace(name='MYCHARM')
2022-01-22 17:06:29.410 Retrieving credentials for 'charmcraft' on HttpUrl('https://api.charmhub.io', scheme='https', host='api.charmhub.io', tld='io', host_type='domain') from keyring 'auth MemoryKeyring'.
2022-01-22 17:06:29.410 Credentials not found in the keyring 'auth MemoryKeyring'
2022-01-22 17:06:29.410 Not logged in.
2022-01-22 17:06:29.412 Traceback (most recent call last):
2022-01-22 17:06:29.412   File "/snap/charmcraft/761/lib/charmcraft/commands/store/client.py", line 94, in request_urlpath_json
2022-01-22 17:06:29.412     response = super().request(method, self.api_base_url + urlpath, *args, **kwargs)
2022-01-22 17:06:29.412   File "/snap/charmcraft/761/lib/craft_store/base_client.py", line 151, in request
2022-01-22 17:06:29.412     headers["Authorization"] = self._get_authorization_header()
2022-01-22 17:06:29.412   File "/snap/charmcraft/761/lib/craft_store/store_client.py", line 96, in _get_authorization_header
2022-01-22 17:06:29.412     auth = self._auth.get_credentials()
2022-01-22 17:06:29.412   File "/snap/charmcraft/761/lib/craft_store/auth.py", line 150, in get_credentials
2022-01-22 17:06:29.412     raise errors.NotLoggedIn()
2022-01-22 17:06:29.412 craft_store.errors.NotLoggedIn: Not logged in.
2022-01-22 17:06:29.412 Full execution log: '/home/MYUSER/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220122-170629.358793.log'

charmcraft version
1.4.0

```

**Comment by EMCP** [comment]
seems I am unable to roll back to prior versions of snaps also.. quite painful as now I cannot put full filepaths in bundle yaml files as a temp workaround like I used to.. 

```
$ snap info charmcraft
name:      charmcraft
summary:   The charming tool
publisher: Canonical✓
store-url: https://snapcraft.io/charmcraft
license:   Apache-2.0
description: |
  Charmcraft enables charm creators to build, publish, and manage charmed operators for Kubernetes,
  metal and virtual machines.
commands:
  - charmcraft
snap-id:      gcqfpVCOUvmDuYT0Dh5PjdeGypSEzNdV
tracking:     latest/stable
refresh-date: today at 18:58 CET
channels:
  latest/stable:    1.4.0             2022-01-21 (761) 59MB classic
  latest/candidate: 1.4.0             2022-01-11 (761) 59MB classic
  latest/beta:      ↑                                       
  latest/edge:      1.4.0+12.g45f65a5 2022-01-18 (771) 59MB classic
installed:          1.4.0                        (761) 59MB classic

```

**Comment by EMCP** [comment]
okay the GREAT news is that bundles now just need full paths to charm files.. that gets me unstuck and very welcome until the login issue gets sorted.. phew

example workaround when you cannot publish your charm 

```
  ibgateway:
    charm: /home/username/Dev/git/some/path/to/your/some-app-20.04-amd64.charm
    num_units: 1
    to:
    - "1"
```

**Comment by facundobatista** [comment]
Hello! Thanks for the report. It looks Charmcraft is failing to find your system's keyring, so the login credentials are not really stored anywhere. This is a VM or any kind of container? thanks!

**Comment by EMCP** [comment]
no worries @facundobatista , thanks for getting back to this

Not in a VM or container.. all charmcraft work I do so far is in a Kubuntu 20.04 machine ..

**Comment by jnsgruk** [comment]
I'm also struggling with this issue since 1.4.0 - `charmcraft login` seems to work but I repeatedly get the above error

**Comment by facundobatista** [comment]
We have a problem about the snap not being able to use all keyrings in all environments that have them (of course, in remote systems where keyrings are not present, the credentials needs to be passed using an environment variable).

@EMCP in Kubuntu, a workaround is to install `gnome-keyring`.

@jnsgruk in which system/environment are you?

Thanks!

**Comment by jnsgruk** [comment]
Ah interesting, I'm on Plasma (on Arch) and `gnome-keyring` isn't installed, I can install it and try.

Just a side note though, does the backend we're using for keyrings *not* support KDE Wallet? Should we not fallback gracefully in this situation and go back to using file based credentials? This seems like a pretty limiting bug?

**Comment by facundobatista** [comment]
We're investigating it. KDE Wallet is not being found by charmcraft from **inside the snap**, we still don't know why.

**Comment by jnsgruk** [comment]
> We're investigating it. KDE Wallet is not being found by charmcraft from **inside the snap**, we still don't know why.

Ah got it. Thanks.

**Comment by Cynerva** [comment]
> of course, in remote systems where keyrings are not present, the credentials needs to be passed using an environment variable

Please correct me if this is wrong, but this is how I got auth to work via the CHARMCRAFT_AUTH env var:

```
$ charmcraft login --export charmcraft-auth
Opening an authorization web page in your browser.
If it does not open, please open this URL:
 ...
Login successful. Credentials exported to 'charmcraft-auth'.

$ export CHARMCRAFT_AUTH=$(cat charmcraft-auth)

$ charmcraft whoami
name: George Kraft
username: cynerva
...
```

**Comment by sed-i** [comment]
I have a different login error:
> Failed to create the collection: Prompt dismissed
> `jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownMethod] ('No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/secrets/collection/login',)`

```
2022-01-25 22:52:59.801 Starting charmcraft version 1.4.0
2022-01-25 22:52:59.802 Raw pre-parsed sysargs: args={'help': False, 'verbose': False, 'quiet': False, 'trace': False, 'project_dir': None} filtered=['login']
2022-01-25 22:52:59.802 General parsed sysargs: command='login' args=[]
2022-01-25 22:52:59.807 Command parsed sysargs: Namespace(bundle=None, channel=None, charm=None, export=None, permission=None, ttl=None)
2022-01-25 22:52:59.980 HTTP 'POST' for 'https://api.charmhub.io/v1/tokens' with params None and headers {'Content-Type': 'application/json', 'Accept': 'application/json', 'User-Agent': 'charmcraft/1.4.0 ubuntu/21.04 (x86_64) python/3.8.10'}
2022-01-25 22:53:01.122 HTTP 'GET' for 'https://api.jujucharms.com/identity/wait-token?did=ecd9b7b9fcc11000d44a7439f842c3ebe72c8db4d75836dddbce2c81a3173df7' with params None and headers {'User-Agent': 'charmcraft/1.4.0 ubuntu/21.04 (x86_64) python/3.8.10'}
2022-01-25 22:53:28.806 HTTP 'POST' for 'https://api.charmhub.io/v1/tokens/exchange' with params None and headers {'Macaroons': '<macaroon>', 'User-Agent': 'charmcraft/1.4.0 ubuntu/21.04 (x86_64) python/3.8.10'}
2022-01-25 22:53:29.225 Storing credentials for 'charmcraft' on HttpUrl('https://api.charmhub.io', scheme='https', host='api.charmhub.io', tld='io', host_type='domain') in keyring 'chainer ChainerBackend'.
2022-01-25 22:53:29.308 charmcraft internal error: InitError('Failed to create the collection: Prompt dismissed..')
2022-01-25 22:53:29.328 Traceback (most recent call last):
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/secretstorage/util.py", line 46, in send_and_get_reply
2022-01-25 22:53:29.328     return self._connection.send_and_get_reply(msg, unwrap=True)
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/jeepney/io/blocking.py", line 190, in send_and_get_reply
2022-01-25 22:53:29.328     return unwrap_msg(msg_in)
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/jeepney/wrappers.py", line 214, in unwrap_msg
2022-01-25 22:53:29.328     raise DBusErrorResponse(msg)
2022-01-25 22:53:29.328 jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownMethod] ('No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/secrets/collection/login',)
2022-01-25 22:53:29.328 
2022-01-25 22:53:29.328 The above exception was the direct cause of the following exception:
2022-01-25 22:53:29.328 Traceback (most recent call last):
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/secretstorage/collection.py", line 161, in get_default_collection
2022-01-25 22:53:29.328     return Collection(connection)
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/secretstorage/collection.py", line 44, in __init__
2022-01-25 22:53:29.328     self._collection.get_property('Label')
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/secretstorage/util.py", line 64, in get_property
2022-01-25 22:53:29.328     (signature, value), = self.send_and_get_reply(msg)
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/secretstorage/util.py", line 49, in send_and_get_reply
2022-01-25 22:53:29.328     raise ItemNotFoundException('Item does not exist!') from resp
2022-01-25 22:53:29.328 secretstorage.exceptions.ItemNotFoundException: Item does not exist!
2022-01-25 22:53:29.328 
2022-01-25 22:53:29.328 During handling of the above exception, another exception occurred:
2022-01-25 22:53:29.328 Traceback (most recent call last):
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/keyring/backends/SecretService.py", line 61, in get_preferred_collection
2022-01-25 22:53:29.328     collection = secretstorage.get_default_collection(bus)
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/secretstorage/collection.py", line 163, in get_default_collection
2022-01-25 22:53:29.328     return create_collection(connection, 'Default',
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/secretstorage/collection.py", line 145, in create_collection
2022-01-25 22:53:29.328     raise PromptDismissedException('Prompt dismissed.')
2022-01-25 22:53:29.328 secretstorage.exceptions.PromptDismissedException: Prompt dismissed.
2022-01-25 22:53:29.328 
2022-01-25 22:53:29.328 During handling of the above exception, another exception occurred:
2022-01-25 22:53:29.328 Traceback (most recent call last):
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/charmcraft/main.py", line 382, in main
2022-01-25 22:53:29.328     retcode = dispatcher.run()
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/charmcraft/main.py", line 346, in run
2022-01-25 22:53:29.328     return self.loaded_command.run(self.parsed_command_args)
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/charmcraft/commands/store/__init__.py", line 197, in run
2022-01-25 22:53:29.328     credentials = store.login(**kwargs)
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/charmcraft/commands/store/store.py", line 211, in login
2022-01-25 22:53:29.328     return self._client.login(**kwargs)
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/charmcraft/commands/store/client.py", line 73, in login
2022-01-25 22:53:29.328     return super().login(*args, **kwargs)
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/craft_store/base_client.py", line 123, in login
2022-01-25 22:53:29.328     self._auth.set_credentials(store_authorized_macaroon)
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/craft_store/auth.py", line 124, in set_credentials
2022-01-25 22:53:29.328     self._keyring.set_password(
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/keyring/backends/chainer.py", line 58, in set_password
2022-01-25 22:53:29.328     return keyring.set_password(service, username, password)
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/keyring/backends/SecretService.py", line 87, in set_password
2022-01-25 22:53:29.328     collection = self.get_preferred_collection()
2022-01-25 22:53:29.328   File "/snap/charmcraft/761/lib/keyring/backends/SecretService.py", line 63, in get_preferred_collection
2022-01-25 22:53:29.328     raise InitError("Failed to create the collection: %s." % e)
2022-01-25 22:53:29.328 keyring.errors.InitError: Failed to create the collection: Prompt dismissed..
2022-01-25 22:53:29.328 Full execution log: '/home/ubuntu/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220125-225259.800554.log'
```

**Comment by gruyaume** [comment]
This issue is also affecting me. I get the "Not logged in message" right after logging in:
```
ubuntu@ip-172-31-57-212:~/charmed-magma/orchestrator-bundle/nms-magmalte-operator$ charmcraft login
Opening an authorization web page in your browser.
If it does not open, please open this URL:
 https://api.jujucharms.com/identity/login?did=2c475e004a04a2969955ab67d1d980a59ebfbcb46414221221b17690aac25470 

Logged in as 'gruyaume'.                                                                                                                                                                                                                               
ubuntu@ip-172-31-57-212:~/charmed-magma/orchestrator-bundle/nms-magmalte-operator$ charmcraft whoami
You are not logged in to Charmhub. 
```

**Comment by EMCP** [comment]
Kubuntu 20.04 is now working after

```
sudo apt install gnome-keyring
```

thank you @facundobatista !
