### ISSUE TITLE
systemctl status systemd-resolved.service

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#645]
Everyone on our team is facing this issue right now.... not sure what to do

```$ make charm
2022-02-02 22:43:53.093 Starting charmcraft version 1.4.0
2022-02-02 22:43:53.093 Logging execution to '/home/bdx/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220202-224353.092676.log'
2022-02-02 22:43:53.096 Packing the charm.
2022-02-02 22:43:53.304 Executing on host: lxc --project default profile show local:default
2022-02-02 22:43:53.400 Launching environment to pack for base name='ubuntu' channel='20.04' architectures=['amd64']
2022-02-02 22:43:53.400 Executing on host: lxc remote list --format=yaml
2022-02-02 22:43:53.481 Remote 'craft-com.ubuntu.cloud-buildd' already exists.
2022-02-02 22:43:53.481 Executing on host: lxc project list local: --format=yaml
2022-02-02 22:43:53.580 Executing on host: lxc --project charmcraft list local: --format=yaml
2022-02-02 22:43:53.790 Executing on host: lxc --project charmcraft list local: --format=yaml
2022-02-02 22:43:54.003 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 cat /etc/os-release
2022-02-02 22:43:54.164 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 test -f /etc/craft-instance.conf
2022-02-02 22:43:54.341 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 cat /etc/craft-instance.conf
2022-02-02 22:43:54.541 Executing on host: lxc --project charmcraft file push /home/bdx/snap/charmcraft/common/tmpp83wiaih local:charmcraft-license-manager-agent-12832062-0-0-amd64/etc/environment --mode=0644
2022-02-02 22:43:54.645 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 chown root:root /etc/environment
2022-02-02 22:43:54.823 Waiting for environment to be ready...
2022-02-02 22:43:54.823 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl is-system-running
2022-02-02 22:43:55.007 Executing on host: lxc --project charmcraft file push /home/bdx/snap/charmcraft/common/tmp5f7p4ykn local:charmcraft-license-manager-agent-12832062-0-0-amd64/etc/craft-instance.conf --mode=0644
2022-02-02 22:43:55.112 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 chown root:root /etc/craft-instance.conf
2022-02-02 22:43:55.300 Executing on host: lxc --project charmcraft file push /home/bdx/snap/charmcraft/common/tmpx6bywx8t local:charmcraft-license-manager-agent-12832062-0-0-amd64/etc/hostname --mode=0644
2022-02-02 22:43:55.402 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 chown root:root /etc/hostname
2022-02-02 22:43:55.584 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 hostname -F /etc/hostname
2022-02-02 22:43:55.773 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
2022-02-02 22:43:55.971 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl enable systemd-resolved
2022-02-02 22:43:56.206 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl restart systemd-resolved
2022-02-02 22:43:56.669 Failed to setup systemd-resolved.
* Command that failed: 'lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl restart systemd-resolved'
* Command exit code: 1
* Command standard error output: b'Job for systemd-resolved.service failed because the control process exited with error code.\nSee "systemctl status systemd-resolved.service" and "journalctl -xe" for details.\n'
2022-02-02 22:43:56.670 Traceback (most recent call last):
2022-02-02 22:43:56.670   File "/snap/charmcraft/761/lib/craft_providers/bases/buildd.py", line 463, in _setup_resolved
2022-02-02 22:43:56.670     executor.execute_run(
2022-02-02 22:43:56.670   File "/snap/charmcraft/761/lib/craft_providers/lxd/lxd_instance.py", line 221, in execute_run
2022-02-02 22:43:56.671     return self.lxc.exec(
2022-02-02 22:43:56.671   File "/snap/charmcraft/761/lib/craft_providers/lxd/lxc.py", line 307, in exec
2022-02-02 22:43:56.671     return runner(final_cmd, **kwargs)  # pylint: disable=subprocess-run-check
2022-02-02 22:43:56.671   File "/snap/charmcraft/761/usr/lib/python3.8/subprocess.py", line 516, in run
2022-02-02 22:43:56.671     raise CalledProcessError(retcode, process.args,
2022-02-02 22:43:56.671 subprocess.CalledProcessError: Command '['lxc', '--project', 'charmcraft', 'exec', 'local:charmcraft-license-manager-agent-12832062-0-0-amd64', '--', 'env', 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'CHARMCRAFT_MANAGED_MODE=1', 'systemctl', 'restart', 'systemd-resolved']' returned non-zero exit status 1.
2022-02-02 22:43:56.671
2022-02-02 22:43:56.671 The above exception was the direct cause of the following exception:
2022-02-02 22:43:56.671 Traceback (most recent call last):
2022-02-02 22:43:56.671   File "/snap/charmcraft/761/lib/charmcraft/providers/_lxd.py", line 177, in launched_environment
2022-02-02 22:43:56.672     instance = lxd.launch(
2022-02-02 22:43:56.672   File "/snap/charmcraft/761/lib/craft_providers/lxd/launcher.py", line 173, in launch
2022-02-02 22:43:56.672     base_configuration.setup(executor=instance)
2022-02-02 22:43:56.672   File "/snap/charmcraft/761/lib/charmcraft/providers/_buildd.py", line 111, in setup
2022-02-02 22:43:56.672     super().setup(executor=executor, retry_wait=retry_wait, timeout=timeout)
2022-02-02 22:43:56.672   File "/snap/charmcraft/761/lib/craft_providers/bases/buildd.py", line 266, in setup
2022-02-02 22:43:56.672     self._setup_resolved(executor=executor, deadline=deadline)
2022-02-02 22:43:56.672   File "/snap/charmcraft/761/lib/craft_providers/bases/buildd.py", line 469, in _setup_resolved
2022-02-02 22:43:56.673     raise BaseConfigurationError(
2022-02-02 22:43:56.673 craft_providers.bases.errors.BaseConfigurationError: Failed to setup systemd-resolved.
2022-02-02 22:43:56.673 * Command that failed: 'lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl restart systemd-resolved'
2022-02-02 22:43:56.673 * Command exit code: 1
2022-02-02 22:43:56.673 * Command standard error output: b'Job for systemd-resolved.service failed because the control process exited with error code.\nSee "systemctl status systemd-resolved.service" and "journalctl -xe" for details.\n'
2022-02-02 22:43:56.673 Full execution log: '/home/bdx/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220202-224353.092676.log'
make: *** [Makefile:21: charm] Error 1
```

**Comment by facundobatista** [comment]
Is this happening? May be a transient issue? (which I do not understand, btw). Thanks!

**Comment by lengau** [comment]
Please let us know if this is still occurring.
