### ISSUE TITLE
Failed to inject host Charmcraft snap into target environment

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#646]
Getting this error consistently

```bash
$ make charm
2022-02-02 22:55:45.249 Starting charmcraft version 1.4.0
2022-02-02 22:55:45.249 Logging execution to '/home/bdx/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220202-225545.248927.log'
2022-02-02 22:55:45.252 Packing the charm.
2022-02-02 22:55:45.458 Executing on host: lxc --project default profile show local:default
2022-02-02 22:55:45.552 Launching environment to pack for base name='ubuntu' channel='20.04' architectures=['amd64']
2022-02-02 22:55:45.553 Executing on host: lxc remote list --format=yaml
2022-02-02 22:55:45.631 Remote 'craft-com.ubuntu.cloud-buildd' already exists.
2022-02-02 22:55:45.631 Executing on host: lxc project list local: --format=yaml
2022-02-02 22:55:45.724 Executing on host: lxc --project charmcraft list local: --format=yaml
2022-02-02 22:55:45.944 Executing on host: lxc --project charmcraft list local: --format=yaml
2022-02-02 22:55:46.154 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 cat /etc/os-release
2022-02-02 22:55:46.324 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 test -f /etc/craft-instance.conf
2022-02-02 22:55:46.518 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 cat /etc/craft-instance.conf
2022-02-02 22:55:46.713 Executing on host: lxc --project charmcraft file push /home/bdx/snap/charmcraft/common/tmp_nq07r0z local:charmcraft-license-manager-agent-12832062-0-0-amd64/etc/environment --mode=0644
2022-02-02 22:55:46.819 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 chown root:root /etc/environment
2022-02-02 22:55:46.993 Waiting for environment to be ready...
2022-02-02 22:55:46.993 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl is-system-running
2022-02-02 22:55:47.162 Executing on host: lxc --project charmcraft file push /home/bdx/snap/charmcraft/common/tmpobwfw2o7 local:charmcraft-license-manager-agent-12832062-0-0-amd64/etc/craft-instance.conf --mode=0644
2022-02-02 22:55:47.263 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 chown root:root /etc/craft-instance.conf
2022-02-02 22:55:47.425 Executing on host: lxc --project charmcraft file push /home/bdx/snap/charmcraft/common/tmp96tkxz24 local:charmcraft-license-manager-agent-12832062-0-0-amd64/etc/hostname --mode=0644
2022-02-02 22:55:47.557 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 chown root:root /etc/hostname
2022-02-02 22:55:47.748 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 hostname -F /etc/hostname
2022-02-02 22:55:47.920 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
2022-02-02 22:55:48.102 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl enable systemd-resolved
2022-02-02 22:55:48.345 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl restart systemd-resolved
2022-02-02 22:55:48.805 Executing on host: lxc --project charmcraft file push /home/bdx/snap/charmcraft/common/tmp07sziqtw local:charmcraft-license-manager-agent-12832062-0-0-amd64/etc/systemd/network/10-eth0.network --mode=0644
2022-02-02 22:55:48.905 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 chown root:root /etc/systemd/network/10-eth0.network
2022-02-02 22:55:49.092 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl enable systemd-networkd
2022-02-02 22:55:49.328 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl restart systemd-networkd
2022-02-02 22:55:49.783 Waiting for networking to be ready...
2022-02-02 22:55:49.784 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 getent hosts snapcraft.io
2022-02-02 22:55:50.363 Executing on host: lxc --project charmcraft file push /home/bdx/snap/charmcraft/common/tmpr6b0qv8z local:charmcraft-license-manager-agent-12832062-0-0-amd64/etc/apt/apt.conf.d/00no-recommends --mode=0644
2022-02-02 22:55:50.473 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 chown root:root /etc/apt/apt.conf.d/00no-recommends
2022-02-02 22:55:50.655 Executing on host: lxc --project charmcraft file push /home/bdx/snap/charmcraft/common/tmpvkiwi1qn local:charmcraft-license-manager-agent-12832062-0-0-amd64/etc/apt/apt.conf.d/00update-errors --mode=0644
2022-02-02 22:55:50.755 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 chown root:root /etc/apt/apt.conf.d/00update-errors
2022-02-02 22:55:50.943 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 apt-get update
2022-02-02 22:55:52.998 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 apt-get install -y apt-utils
2022-02-02 22:55:53.711 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 apt-get install -y fuse udev
2022-02-02 22:55:54.298 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl enable systemd-udevd
2022-02-02 22:55:54.542 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl start systemd-udevd
2022-02-02 22:55:54.724 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 apt-get install -y snapd
2022-02-02 22:55:55.339 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl start snapd.socket
2022-02-02 22:55:55.518 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 systemctl restart snapd.service
2022-02-02 22:55:55.767 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 snap wait system seed.loaded
2022-02-02 22:55:55.939 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 rm -f /tmp/charmcraft.snap
2022-02-02 22:55:56.279 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 test -d /tmp
2022-02-02 22:55:56.453 Executing on host: lxc --project charmcraft file push /home/bdx/tmpg3dnpdc3.tmp-craft/charmcraft.snap local:charmcraft-license-manager-agent-12832062-0-0-amd64/tmp/charmcraft.snap --gid=0 --uid=0
2022-02-02 22:55:58.664 Executing in container: lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 snap install /tmp/charmcraft.snap --classic --dangerous
2022-02-02 22:56:06.427 Failed to inject host Charmcraft snap into target environment.
2022-02-02 22:56:06.428 Traceback (most recent call last):
2022-02-02 22:56:06.428   File "/snap/charmcraft/761/lib/craft_providers/actions/snap_installer.py", line 135, in inject_from_host
2022-02-02 22:56:06.428     executor.execute_run(
2022-02-02 22:56:06.428   File "/snap/charmcraft/761/lib/craft_providers/lxd/lxd_instance.py", line 221, in execute_run
2022-02-02 22:56:06.428     return self.lxc.exec(
2022-02-02 22:56:06.428   File "/snap/charmcraft/761/lib/craft_providers/lxd/lxc.py", line 307, in exec
2022-02-02 22:56:06.428     return runner(final_cmd, **kwargs)  # pylint: disable=subprocess-run-check
2022-02-02 22:56:06.428   File "/snap/charmcraft/761/usr/lib/python3.8/subprocess.py", line 516, in run
2022-02-02 22:56:06.428     raise CalledProcessError(retcode, process.args,
2022-02-02 22:56:06.428 subprocess.CalledProcessError: Command '['lxc', '--project', 'charmcraft', 'exec', 'local:charmcraft-license-manager-agent-12832062-0-0-amd64', '--', 'env', 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'CHARMCRAFT_MANAGED_MODE=1', 'snap', 'install', '/tmp/charmcraft.snap', '--classic', '--dangerous']' returned non-zero exit status 1.
2022-02-02 22:56:06.428
2022-02-02 22:56:06.429 The above exception was the direct cause of the following exception:
2022-02-02 22:56:06.429 Traceback (most recent call last):
2022-02-02 22:56:06.429   File "/snap/charmcraft/761/lib/charmcraft/providers/_buildd.py", line 80, in _setup_charmcraft
2022-02-02 22:56:06.429     snap_installer.inject_from_host(
2022-02-02 22:56:06.429   File "/snap/charmcraft/761/lib/craft_providers/actions/snap_installer.py", line 143, in inject_from_host
2022-02-02 22:56:06.429     raise SnapInstallationError(
2022-02-02 22:56:06.429 craft_providers.actions.snap_installer.SnapInstallationError: Failed to inject snap 'charmcraft'.
2022-02-02 22:56:06.429 * Command that failed: 'lxc --project charmcraft exec local:charmcraft-license-manager-agent-12832062-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 snap install /tmp/charmcraft.snap --classic --dangerous'
2022-02-02 22:56:06.429 * Command exit code: 1
2022-02-02 22:56:06.430 * Command standard error output: b'error: cannot perform the following tasks:\n- Setup snap "charmcraft" (unset) security profiles (cannot find installed snap "charmcraft" at revision x1: missing file /snap/charmcraft/x1/meta/snap.yaml)\n- Run configure hook of "charmcraft" snap if present (run hook "configure": /usr/bin/env: \xe2\x80\x98python3\xe2\x80\x99: No such file or directory)\n'
2022-02-02 22:56:06.430
2022-02-02 22:56:06.430 The above exception was the direct cause of the following exception:
2022-02-02 22:56:06.430 Traceback (most recent call last):
2022-02-02 22:56:06.430   File "/snap/charmcraft/761/lib/charmcraft/providers/_lxd.py", line 177, in launched_environment
2022-02-02 22:56:06.430     instance = lxd.launch(
2022-02-02 22:56:06.430   File "/snap/charmcraft/761/lib/craft_providers/lxd/launcher.py", line 173, in launch
2022-02-02 22:56:06.430     base_configuration.setup(executor=instance)
2022-02-02 22:56:06.430   File "/snap/charmcraft/761/lib/charmcraft/providers/_buildd.py", line 113, in setup
2022-02-02 22:56:06.430     self._setup_charmcraft(executor=executor)
2022-02-02 22:56:06.431   File "/snap/charmcraft/761/lib/charmcraft/providers/_buildd.py", line 84, in _setup_charmcraft
2022-02-02 22:56:06.431     raise bases.BaseConfigurationError(
2022-02-02 22:56:06.431 craft_providers.bases.errors.BaseConfigurationError: Failed to inject host Charmcraft snap into target environment.
2022-02-02 22:56:06.431 Full execution log: '/home/bdx/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220202-225545.248927.log'
make: *** [Makefile:21: charm] Error 1
```

**Comment by vvv-z** [comment]
You may try to run "charmcraft clean --verbose" first.
This solved the same issue for me.

**Comment by lengau** [comment]
I've not been able to reproduce this with recent charmcrafts. Please reopen if it's still happening for you
