### ISSUE TITLE
[1.5.0] Charmcraft login not finding keyring

### ISSUE THREAD

**Issue by phvalguima** [canonical/charmcraft#719]
Hi,

My snap has upgraded to: 1.5.0+7.g51565d8

When I run:
```
$ sudo -u <user> charmcraft login
No keyring found to store or retrieve credentials from.                                                                                                                         
Full execution log: ...
```

Running the same command with debug option returns:
```
$ sudo -u <user> charmcraft login -v
2022-03-18 15:52:12.112 Starting charmcraft version 1.5.0+7.g51565d8                                                                                                            
2022-03-18 15:52:12.112 Logging execution to                 
2022-03-18 15:52:12.199 No keyring found to store or retrieve credentials from.                                                                                                 
2022-03-18 15:52:12.200 Traceback (most recent call last):                                                                                                                      
2022-03-18 15:52:12.200   File "/snap/charmcraft/849/lib/charmcraft/commands/store/store.py", line 179, in __init__                                                             
2022-03-18 15:52:12.200     self._client = Client(charmhub_config.api_url, charmhub_config.storage_url)                                                                         
2022-03-18 15:52:12.200   File "/snap/charmcraft/849/lib/charmcraft/commands/store/client.py", line 57, in __init__                                                             
2022-03-18 15:52:12.200     super().__init__(                                                                                                                                   
2022-03-18 15:52:12.200   File "/snap/charmcraft/849/lib/craft_store/store_client.py", line 84, in __init__                                                                     
2022-03-18 15:52:12.200     super().__init__(                                                                                                                                   
2022-03-18 15:52:12.200   File "/snap/charmcraft/849/lib/craft_store/base_client.py", line 65, in __init__                                                                      
2022-03-18 15:52:12.200     self._auth = Auth(                                                                                                                                  
2022-03-18 15:52:12.200   File "/snap/charmcraft/849/lib/craft_store/auth.py", line 103, in __init__                                                                            
2022-03-18 15:52:12.200     raise errors.NoKeyringError()                                                                                                                       
2022-03-18 15:52:12.200 craft_store.errors.NoKeyringError: No keyring found to store or retrieve credentials from.  
```

Which fails in this check:
```
...
        self._keyring = keyring.get_keyring()
        # This keyring would fail on first use, fail early instead.
        if isinstance(self._keyring, keyring.backends.fail.Keyring): ## <<<<----------------------
            raise errors.NoKeyringError()
...
```

However, if I manually install the same keyring lib (23.5.0) and just run it, I get:
```
$ sudo -u <user> python3 -c "import keyring; key=keyring.get_keyring(); print(key)"
keyring.backends.libsecret.Keyring (priority: 4.8)
```

I was expecting to actually see ```keyring.backends.fail.Keyring```, just like it happens with auth.py above.

Nonetheless, I'd expect ```charmcraft login``` to always work, even if I do not have a keyring. Or at least give me exact steps of what I should be doing as an user to setup the keyring and login.

Also, I am using "sudo" just because my original user was logged in with charmcraft when we used to have v1.4.0 and I could not reproduce the issue with that user. When running with sudo, it likely misses some of the variables needed to correctly configure charmcraft.

Workaround:
```
$ keyring --list # select one of the keyrings
$ sudo -u <user> PYTHON_KEYRING_BACKEND=<chose-keyring> charmcraft login
```

**Comment by jardon** [comment]
My system for whatever reason doesnt have the SecretService keyring as seen here:
```
$ keyring --list
keyring.backends.chainer.ChainerBackend (priority: -1)
keyring.backends.fail.Keyring (priority: 0)
```
I do have the following packages installed which should included the required bits:
```
$ dpkg -l | grep -i secret
ii  gir1.2-secret-1:amd64                         0.20.4-2                                               amd64        Secret store (GObject-Introspection)
ii  libsecret-1-0:amd64                           0.20.4-2                                               amd64        Secret store
ii  libsecret-common                              0.20.4-2                                               all          Secret store (common files)
ii  libsecret-tools                               0.20.4-2                                               amd64        tool for storing and retrieving GObject passwords
ii  python3-secretstorage                         3.3.1-1                                                all          Python module for storing secrets - Python 3.x version
```

**Comment by sergiusens** [comment]
@jardon do you have a seat? Usually provided by a desktop session or is this a VM or container somewhere?

**Comment by sed-i** [comment]
I have the same problem inside a VM.

**Comment by phvalguima** [comment]
re: @jardon's comment, I have that keyring and still have the same issue:

```
$ sudo -u <user> keyring --list
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.chainer.ChainerBackend (priority: -10)
keyring.backends.SecretService.Keyring (priority: 5)
```

I don't think this is related to a given keyring being present or missing. I'd guess that when running the charmcraft, the ```keyring.backends.fail.Keyring``` has the highest priority for some reason. It must have access to my other keyrings though, when I set ```PYTHON_KEYRING_BACKEND```, it works.

**Comment by sergiusens** [comment]
Can I get more information here? What Desktop Environment is this run on, is there a running dbus-session? Is this using KDEWallet5 or gnome-keyring?

**Comment by sergiusens** [comment]
@sed-i I would advise that if the same workaround does not work, that this is a different issue

**Comment by jardon** [comment]
This is actually on a Cosmis desktop which uses gnome-keyring running on baremetal

**Comment by sergiusens** [comment]
thanks for the insight, I will create a VM with that to try and reproduce, can you clarify the version of Cosmic you are using?

Your issue however does look different to @phvalguima's

**Comment by sed-i** [comment]
With the [charm-dev blueprint](https://github.com/canonical/multipass-blueprints/blob/main/v1/charm-dev.yaml), after installing `libsecret-tools` and `gnome-keyring`, 

```
ubuntu@charm-dev:~$ keyring --list
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.SecretService.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: -10)

ubuntu@charm-dev:~$ python3 -c "import keyring; key=keyring.get_keyring(); print(key)"
keyring.backends.SecretService.Keyring (priority: 5)
```

none of the following work for me:

1. `charmcraft login` [log1.log](https://github.com/canonical/charmcraft/files/8394735/log1.log)
2. `dbus-run-session -- charmcraft login` (freezes) [log2.log](https://github.com/canonical/charmcraft/files/8394740/log2.log)
3. `PYTHON_KEYRING_BACKEND=keyring.backends.SecretService.Keyring charmcraft login` [log3.log](https://github.com/canonical/charmcraft/files/8394742/log3.log)

**Comment by sergiusens** [comment]
It is a bit more involved on headless systems have you tried following https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems ?

**Comment by sed-i** [comment]
> It is a bit more involved on headless systems have you tried following https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems ?

Yes, that works! Thanks.

**Comment by sed-i** [comment]
Fwiw, here's a one liner
```bash
dbus-run-session -- bash -c "echo password | gnome-keyring-daemon --unlock; charmcraft fetch-lib"
```
