### ISSUE TITLE
charmcraft revisions Broken pipe on head / tail commands

### ISSUE THREAD

**Issue by claudiubelu** [canonical/charmcraft#721]
When running ``charmcraft revisions charm-name | head -n 2``, the expectation would be to get the top 2 lines from the ``charmcraft revisions`` command. The command results in a ``BrokenPipeError`` error.

OS: Ubuntu 20.04.3
Charmcraft version: 1.5.0

Sample:

```
charmcraft revisions finos-legend-sdlc-k8s | head -n 2
Revision    Version    Created at    Status
41          41         2022-03-17    released
Traceback (most recent call last):
  File "/snap/charmcraft/834/lib/charmcraft/main.py", line 167, in main
    retcode = dispatcher.run()
  File "/snap/charmcraft/834/lib/craft_cli/dispatcher.py", line 400, in run
    return self._loaded_command.run(self._parsed_command_args)
  File "/snap/charmcraft/834/lib/charmcraft/commands/store/__init__.py", line 597, in run
    emit.message(line)
  File "/snap/charmcraft/834/lib/craft_cli/messages.py", line 610, in func
    return wrapped_func(self, *args, **kwargs)
  File "/snap/charmcraft/834/lib/craft_cli/messages.py", line 712, in message
    self._printer.show(sys.stdout, text, use_timestamp=use_timestamp)  # type: ignore
  File "/snap/charmcraft/834/lib/craft_cli/messages.py", line 373, in show
    self._show(msg)
  File "/snap/charmcraft/834/lib/craft_cli/messages.py", line 333, in _show
    self._write_line(msg)
  File "/snap/charmcraft/834/lib/craft_cli/messages.py", line 281, in _write_line
    print(line, end="", flush=True, file=message.stream)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/charmcraft/834/bin/charmcraft", line 8, in <module>
    sys.exit(main())
  File "/snap/charmcraft/834/lib/charmcraft/main.py", line 192, in main
    emit.error(error)
  File "/snap/charmcraft/834/lib/craft_cli/messages.py", line 610, in func
    return wrapped_func(self, *args, **kwargs)
  File "/snap/charmcraft/834/lib/craft_cli/messages.py", line 827, in error
    self._report_error(error)
  File "/snap/charmcraft/834/lib/craft_cli/messages.py", line 801, in _report_error
    self._printer.show(sys.stderr, str(error), use_timestamp=use_timestamp, end_line=True)  # type: ignore
  File "/snap/charmcraft/834/lib/craft_cli/messages.py", line 373, in show
    self._show(msg)
  File "/snap/charmcraft/834/lib/craft_cli/messages.py", line 333, in _show
    self._write_line(msg)
  File "/snap/charmcraft/834/lib/craft_cli/messages.py", line 262, in _write_line
    print(flush=True, file=self.prv_msg.stream)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by facundobatista** [comment]
This improvement is already in place after started using enhanced Craft CLI, in latest Charmcraft:

```
$ charmcraft version
2.0.0                                                                                                                                      
$ charmcraft revisions my-super-charm | head -n 2
Revision    Version    Created at            Status
18          7.4a       2022-08-22T12:03:57Z  approved
$ charmcraft revisions my-super-charm | wc
     14      57     754
```
