### ISSUE TITLE
Error when executing `pack` on mac – '20.04' is not a supported alias

### ISSUE THREAD

**Issue by jon-ruckwood** [canonical/charmcraft#757]
I'm getting an error whilst attempting to execute `charmcraft pack` on Mac for the `hello-kubecon` sample. The README suggests I should be able to just execute `pack` to build.

```shell
$ charmcraft version
1.6.0

$ multipass version
multipass   1.8.1+mac
multipassd  1.8.1+mac
```

To reproduce the issue:
```shell
$ git clone https://github.com/jnsgruk/hello-kubecon && cd hello-kubecon
$ charmcraft pack
Failed to launch VM 'charmcraft-hello-kubecon-48216365-0-0-amd64'.4' architect…
* Command that failed: 'multipass launch snapcraft:20.04 --name charmcraft-hello-kubecon-48216365-0-0-amd64 --cpus 2 --mem 2G --disk 64G'
* Command exit code: 2
* Command output: b'\r                                                                                \r\r                                                                                \r'
* Command standard error output: b"launch failed: '20.04' is not a supported alias. Please use `multipass find` for supported image aliases.\n"                                                                              
Full execution log: '/Users/joebloggs/Library/Logs/charmcraft/charmcraft-20220427-165007.397892.log'
```

File `charmcraft-20220427-165007.397892.log`:
 
<details>

```
2022-04-27 16:50:07.398 Starting charmcraft version 1.6.0
2022-04-27 16:50:07.398 Raw pre-parsed sysargs: args={'help': False, 'verbose': False, 'quiet': False, 'trace': False, 'project_dir': None} filtered=['pack']
2022-04-27 16:50:07.398 General parsed sysargs: command='pack' args=[]
2022-04-27 16:50:07.401 Command parsed sysargs: Namespace(debug=False, destructive_mode=False, entrypoint=None, requirement=None, shell=False, shell_after=False, bases_index=None, force=False)
2022-04-27 16:50:07.401 System details: OSPlatform(system='Darwin', release='21.4.0', machine='x86_64'); Environment: None
2022-04-27 16:50:07.401 Packing the charm.
2022-04-27 16:50:07.401 Working arguments: {'from': PosixPath('/Users/joebloggs/Projects/com/github/juju/hello-kubecon'), 'destructive_mode': False, 'entrypoint': None, 'requirement': [], 'bases_indices': None, 'force': False, 'debug': False, 'shell': False, 'shell_after': False}
2022-04-27 16:50:07.401 Parsing '/Users/joebloggs/Projects/com/github/juju/hello-kubecon/metadata.yaml'
2022-04-27 16:50:07.404 Executing on host: multipass version
2022-04-27 16:50:07.469 Building for 'bases[0]' as host matches 'build-on[0]'.
2022-04-27 16:50:07.469 Building for 'bases[0][0]'.
2022-04-27 16:50:07.469 Launching environment to pack for base name='ubuntu' channel='20.04' architectures=['amd64'] (may take a while the first time but it's reusable)
2022-04-27 16:50:07.470 Executing on host: multipass list --format json
2022-04-27 16:50:07.532 Executing on host: multipass launch snapcraft:20.04 --name charmcraft-hello-kubecon-48216365-0-0-amd64 --cpus 2 --mem 2G --disk 64G
2022-04-27 16:50:07.593 Failed to launch VM 'charmcraft-hello-kubecon-48216365-0-0-amd64'.
* Command that failed: 'multipass launch snapcraft:20.04 --name charmcraft-hello-kubecon-48216365-0-0-amd64 --cpus 2 --mem 2G --disk 64G'
* Command exit code: 2
* Command output: b'\r                                                                                \r\r                                                                                \r'
* Command standard error output: b"launch failed: '20.04' is not a supported alias. Please use `multipass find` for supported image aliases.\n"
2022-04-27 16:50:07.594 Traceback (most recent call last):
2022-04-27 16:50:07.594   File "/usr/local/Cellar/charmcraft/1.6.0/libexec/lib/python3.9/site-packages/craft_providers/multipass/multipass.py", line 178, in launch
2022-04-27 16:50:07.594     self._run(command, capture_output=True, check=True)
2022-04-27 16:50:07.594   File "/usr/local/Cellar/charmcraft/1.6.0/libexec/lib/python3.9/site-packages/craft_providers/multipass/multipass.py", line 68, in _run
2022-04-27 16:50:07.594     return subprocess.run(command, check=check, **kwargs)
2022-04-27 16:50:07.594   File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
2022-04-27 16:50:07.594     raise CalledProcessError(retcode, process.args,
2022-04-27 16:50:07.594 subprocess.CalledProcessError: Command '['multipass', 'launch', 'snapcraft:20.04', '--name', 'charmcraft-hello-kubecon-48216365-0-0-amd64', '--cpus', '2', '--mem', '2G', '--disk', '64G']' returned non-zero exit status 2.
2022-04-27 16:50:07.594 
2022-04-27 16:50:07.594 The above exception was the direct cause of the following exception:
2022-04-27 16:50:07.594 Traceback (most recent call last):
2022-04-27 16:50:07.594   File "/usr/local/Cellar/charmcraft/1.6.0/libexec/lib/python3.9/site-packages/charmcraft/providers/_multipass.py", line 166, in launched_environment
2022-04-27 16:50:07.594     instance = multipass.launch(
2022-04-27 16:50:07.594   File "/usr/local/Cellar/charmcraft/1.6.0/libexec/lib/python3.9/site-packages/craft_providers/multipass/_launch.py", line 76, in launch
2022-04-27 16:50:07.594     instance.launch(
2022-04-27 16:50:07.594   File "/usr/local/Cellar/charmcraft/1.6.0/libexec/lib/python3.9/site-packages/craft_providers/multipass/multipass_instance.py", line 287, in launch
2022-04-27 16:50:07.594     self._multipass.launch(
2022-04-27 16:50:07.594   File "/usr/local/Cellar/charmcraft/1.6.0/libexec/lib/python3.9/site-packages/craft_providers/multipass/multipass.py", line 180, in launch
2022-04-27 16:50:07.594     raise MultipassError(
2022-04-27 16:50:07.594 craft_providers.multipass.errors.MultipassError: Failed to launch VM 'charmcraft-hello-kubecon-48216365-0-0-amd64'.
2022-04-27 16:50:07.594 * Command that failed: 'multipass launch snapcraft:20.04 --name charmcraft-hello-kubecon-48216365-0-0-amd64 --cpus 2 --mem 2G --disk 64G'
2022-04-27 16:50:07.594 * Command exit code: 2
2022-04-27 16:50:07.594 * Command output: b'\r                                                                                \r\r                                                                                \r'
2022-04-27 16:50:07.594 * Command standard error output: b"launch failed: '20.04' is not a supported alias. Please use `multipass find` for supported image aliases.\n"
2022-04-27 16:50:07.594 Full execution log: '/Users/joebloggs/Library/Logs/charmcraft/charmcraft-20220427-165007.397892.log'
```

</details>

Result of `multipass find`:
```
$ multipass find         
Image                       Aliases           Version          Description
18.04                       bionic            20220424         Ubuntu 18.04 LTS
20.04                       focal,lts         20220419         Ubuntu 20.04 LTS
21.10                       impish            20220309         Ubuntu 21.10
anbox-cloud-appliance                         latest           Anbox Cloud Appliance
charm-dev                                     latest           A development and testing environment for charmers
docker                                        latest           A Docker environment with Portainer and related tools
minikube                                      latest           minikube is local Kubernetes
```

Contents of [`charmcraft.yaml`][0]:

```yaml
type: charm
bases:
  - build-on:
      - name: "ubuntu"
        channel: "20.04"
    run-on:
      - name: "ubuntu"
        channel: "20.04"
parts:
  charm:
    build-packages:
      - git 
```

I found [this recent change in `_multipass.py`][1] and I think it could be related:

```diff
-   image_name=base.channel,
+   image_name=f"snapcraft:{base.channel}",
```

I was thinking about submitting a PR but I don't have the full picture. Thanks.

[0]: https://github.com/jnsgruk/hello-kubecon/blob/master/charmcraft.yaml
[1]: https://github.com/canonical/charmcraft/blob/main/charmcraft/providers/_multipass.py#L169

**Comment by sergiusens** [comment]
Hi, that highlighted change was related to not being able to launch any multipass image.
Are you on the latest release of multipass? Can you `multipass launch snapcraft:core22`?

**Comment by jon-ruckwood** [comment]
I'm on version `1.8.1+mac` of `multipass` – it was installed when I ran `charmcraft pack` for the first time. It looks like it's the latest released version.

Here's the result of the command:
```shell
multipass launch snapcraft:core22
launch failed: 'core22' is not a supported alias. Please use `multipass find` for supported image aliases.
```

> Hi, that highlighted change was related to not being able to launch any multipass image.

Ok, I suspected the change might be an issue because I observed that the failing command without the `snapcraft:` prefix did work on my system:

```shell
multipass launch 20.04 --name charmcraft-hello-kubecon-48216365-0-0-amd64 --cpus 2 --mem 2G --disk 64G
```

But as I mentioned, it was a bit of stab in the dark. Thanks for taking a look into this.

**Comment by sergiusens** [comment]
Sorry, I have core22 on my mind and that is not yet available on Multipass, can you try and launch `multipass launch snapcraft:core20`

**Comment by jon-ruckwood** [comment]
Yes, that does work. I can see the image being retrieved.

**Comment by facundobatista** [comment]
@jon-ruckwood hello! Taking in consideration that `multipass launch snapcraft:core20` worked ok, now your `charmcraft pack` ends successfully? 

If not, can you try these two commands and show me the output?
- `multipass find` (once again)
- `multipass launch snapcraft:20.04`

Thank you!!

**Comment by lengau** [comment]
Closing this as stale. If you're still seeing this issue please reopen 🙂
