### ISSUE TITLE
charmcraft installation via PIP started failing recently

### ISSUE THREAD

**Issue by EMCP** [canonical/charmcraft#758]
I utilize charmcraft inside a docker container... which rebuilds every 30 days.. or so.  Anyway, it was working fine until a day ago

```
FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt upgrade -y

RUN apt install python3 python3-pip libffi-dev libapt-pkg-dev libssl-dev python3-venv -y

RUN pip3 install https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/python-apt/2.2.1/python-apt_2.2.1.tar.xz
RUN pip3 install charmcraft

RUN charmcraft version
RUN python3 --version

```

The main error I see is the following

```
Step 8/9 : RUN charmcraft version
 ---> Running in d2c85fdeb3a6
Traceback (most recent call last):
  File "/usr/local/bin/charmcraft", line 5, in <module>
    from charmcraft.main import main
  File "/usr/local/lib/python3.8/dist-packages/charmcraft/main.py", line 36, in <module>
    from charmcraft import config, __version__, env, utils
  File "/usr/local/lib/python3.8/dist-packages/charmcraft/config.py", line 81, in <module>
    from charmcraft.parts import validate_part
  File "/usr/local/lib/python3.8/dist-packages/charmcraft/parts.py", line 26, in <module>
    from craft_parts import LifecycleManager, Step, plugins
  File "/usr/local/lib/python3.8/dist-packages/craft_parts/__init__.py", line 21, in <module>
    from . import plugins
  File "/usr/local/lib/python3.8/dist-packages/craft_parts/plugins/__init__.py", line 20, in <module>
    from .plugins import (
  File "/usr/local/lib/python3.8/dist-packages/craft_parts/plugins/plugins.py", line 34, in <module>
    from .rust_plugin import RustPlugin
  File "/usr/local/lib/python3.8/dist-packages/craft_parts/plugins/rust_plugin.py", line 35, in <module>
    UniqueStrList = conlist(str, unique_items=True)
  File "pydantic/types.py", line 509, in pydantic.types.conlist
TypeError: conlist() got an unexpected keyword argument 'unique_items'
The command '/bin/sh -c charmcraft version' returned a non-zero code: 1
```

**Comment by EMCP** [comment]
im trying now to bump to `22:04` as well as bump the apt piece..

is https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/python-apt/2.3.0ubuntu2/python-apt_2.3.0ubuntu2.tar.xz looking correct?

**Comment by facundobatista** [comment]
The problem is that it's bringing a new version of craft-parts which uses a feature from pydantic that is not in the pinned version.

I'm already [in the process of fixing the problem](https://github.com/canonical/charmcraft/pull/765), but to easily fix it for your case, just replace the `RUN pip3 install charmcraft` line in your dockerfile with `RUN pip3 install craft-parts==1.4.2 charmcraft`.
