### ISSUE TITLE
Exported login does not support allowing bundle access

### ISSUE THREAD

**Issue by tasdomas** [canonical/charmcraft#778]
If I export charmcraft credentials `charmcraft login --export auth.file --bundle a-registered-bundle` and try to use them when uploading the bundle, I get an error:
```
- permission-required: Package access not allowed 
```

The log contains:

```
2022-05-30 10:52:42.602 HTTP 'POST' for 'https://storage.snapcraftcontent.com/unscanned-upload/' with params None and headers {'Content-Type': 'multipart/form-data; boundary=43b02f5550094699bf6e5f8ce713c3f4', 'Accept': 'application/json', 'Authorization': '<macaroon>', 'User-Agent': 'charmcraft/1.6.0 ubuntu/20.04 (x86_64) python/3.8.10'}
2022-05-30 10:52:43.518 Uploading bytes ended, id f0b76a0d-3d9e-445c-a212-58aa6fa4a8c4
2022-05-30 10:52:43.519 Retrieving credentials for 'charmcraft' on 'api.charmhub.io' from keyring 'auth MemoryKeyring'.
2022-05-30 10:52:43.519 HTTP 'POST' for 'https://api.charmhub.io/v1/charm/<REDACTED>/revisions' with params None and headers {'Authorization': '<macaroon>', 'User-Agent': 'charmcraft/1.6.0 ubuntu/20.04 (x86_64) python/3.8.10'}
2022-05-30 10:52:44.828 Store operation failed:
- permission-required: Package access not allowed
2022-05-30 10:52:44.830 Traceback (most recent call last):
2022-05-30 10:52:44.830   File "/snap/charmcraft/904/lib/charmcraft/commands/store/store.py", line 140, in error_decorator
2022-05-30 10:52:44.830     return method(self, *args, **kwargs)
2022-05-30 10:52:44.830   File "/snap/charmcraft/904/lib/charmcraft/commands/store/store.py", line 296, in upload
2022-05-30 10:52:44.830     return self._upload(endpoint, filepath)
2022-05-30 10:52:44.830   File "/snap/charmcraft/904/lib/charmcraft/commands/store/store.py", line 268, in _upload
2022-05-30 10:52:44.830     response = self._client.request_urlpath_json("POST", endpoint, json=payload)
2022-05-30 10:52:44.830   File "/snap/charmcraft/904/lib/charmcraft/commands/store/client.py", line 90, in request_urlpath_json
2022-05-30 10:52:44.830     response = super().request(method, self.api_base_url + urlpath, *args, **kwargs)
2022-05-30 10:52:44.830   File "/snap/charmcraft/904/lib/craft_store/base_client.py", line 171, in request
2022-05-30 10:52:44.830     return self.http_client.request(
2022-05-30 10:52:44.830   File "/snap/charmcraft/904/lib/craft_store/http_client.py", line 166, in request
2022-05-30 10:52:44.830     raise errors.StoreServerError(response)
2022-05-30 10:52:44.830 craft_store.errors.StoreServerError: Store operation failed:
2022-05-30 10:52:44.830 - permission-required: Package access not allowed
2022-05-30 10:52:44.830 Full execution log: '/home/d/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220530-105242.595892.log'

```

**Comment by facundobatista** [comment]
Hello! Thanks for the report.

Some questions so we can dig deeper in this issue.

- Can you confirm that you're the owner or a collaborator of `a-registered-bundle`?
- Which is your username in Charmhub?
- How are you using `auth.file` when uploading the bundle?

Finally, please provide the complete log file.

Thanks again!

**Comment by tasdomas** [comment]
Yes, I'm the owner of the bundle
The username is `tasdomas`
I use the `auth.file` as `export CHARMCRAFT_AUTH=$(cat auth.file)`
[charmcraft.log](https://github.com/canonical/charmcraft/files/8799225/charmcraft.log)

**Comment by facundobatista** [comment]
The fix for this is released in Charmhub.
