### ISSUE TITLE
Closed/removed track still shows up in charmhub, juju, but not charmcraft status

### ISSUE THREAD

**Issue by ajkavanagh** [canonical/charmcraft#785]
# Context/background:

* charmcraft 1.7.1 and 1.5
* juju 2.9.31
* charm: mysql-innodb-cluster

Originally, there was a 8.0.19 track; a 8.0 track was added, and the 8.0.19 track was requested to be 'removed'. The 8.0 track is the default track.

However, juju and charmhub.io both show the 8.0.19 track; charmcraft does not.

The "https://api.charmhub.io/v2/charms/info/mysql-innodb-cluster?fields=channel-map" endpoint also lists the 8.0.19 track entries.

juju info mysql-innodb-cluster:

```
name: mysql-innodb-cluster
charm-id: i5HWuKoEat09854Sz0qXHOjmr4wwHLfP
summary: MySQL InnoDB Cluster
publisher: OpenStack Charmers
supports: focal, jammy
tags: cloud, databases
subordinate: false
store-url: https://charmhub.io/mysql-innodb-cluster
description: |
  MySQL InnoDB Cluster Charm deploys and manages the lifecycle of a
  MySQL InnoDB Cluster.
relations:
  provides:
    db-monitor: mysql-monitor
    db-router: mysql-router
    shared-db: mysql-shared
  requires:
    certificates: tls-certificates
channels: |
  8.0/stable: be2f3d1 2022-06-13 (26) 14MB
  8.0/candidate: ↑
  8.0/beta: ↑
  8.0/edge: ↑
  latest/stable: 15 2022-02-09 (15) 13MB
  latest/candidate: ↑
  latest/beta: ↑
  latest/edge: 773bcae 2022-06-01 (27) 14MB
  8.0.19/stable: be2f3d1 2022-05-05 (24) 14MB
  8.0.19/candidate: be2f3d1 2022-04-28 (24) 14MB
  8.0.19/beta: ↑
  8.0.19/edge: be2f3d1 2022-04-27 (24) 14MB
```

```
$ charmcraft status mysql-innodb-cluster

Track Base Channel Version Revision Resources
latest ubuntu 19.10 (all) stable 3 3 mysql-shell (r0)
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
         ubuntu 20.04 (all) stable 15 15 mysql-shell (r0)
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
         ubuntu 20.04 (amd64) stable - - -
                                 candidate - - -
                                 beta - - -
                                 edge 773bcae 27 -
         ubuntu 20.04 (arm64) stable - - -
                                 candidate - - -
                                 beta - - -
                                 edge 773bcae 27 -
         ubuntu 20.04 (ppc64el) stable - - -
                                 candidate - - -
                                 beta - - -
                                 edge 773bcae 27 -
         ubuntu 20.04 (s390x) stable - - -
                                 candidate - - -
                                 beta - - -
                                 edge 773bcae 27 -
         ubuntu 20.10 (all) stable 15 15 mysql-shell (r0)
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
         ubuntu 21.04 (all) stable 15 15 mysql-shell (r0)
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
         ubuntu 21.10 (all) stable 15 15 mysql-shell (r0)
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
         ubuntu 22.04 (amd64) stable - - -
                                 candidate - - -
                                 beta - - -
                                 edge 773bcae 27 -
         ubuntu 22.04 (arm64) stable - - -
                                 candidate - - -
                                 beta - - -
                                 edge 773bcae 27 -
         ubuntu 22.04 (ppc64el) stable - - -
                                 candidate - - -
                                 beta - - -
                                 edge 773bcae 27 -
         ubuntu 22.04 (s390x) stable - - -
                                 candidate - - -
                                 beta - - -
                                 edge 773bcae 27 -
5.7 - stable - - -
                                 candidate - - -
                                 beta - - -
                                 edge - - -
8.0 ubuntu 20.04 (amd64) stable be2f3d1 26 -
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
         ubuntu 20.04 (arm64) stable be2f3d1 26 -
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
         ubuntu 20.04 (ppc64el) stable be2f3d1 26 -
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
         ubuntu 20.04 (s390x) stable be2f3d1 26 -
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
         ubuntu 22.04 (amd64) stable be2f3d1 26 -
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
         ubuntu 22.04 (arm64) stable be2f3d1 26 -
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
         ubuntu 22.04 (ppc64el) stable be2f3d1 26 -
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
         ubuntu 22.04 (s390x) stable be2f3d1 26 -
                                 candidate ↑ ↑ ↑
                                 beta ↑ ↑ ↑
                                 edge ↑ ↑ ↑
```

When charmcraft tries to close a risk on the 8.0.19 track:

```
$ charmcraft close mysql-innodb-cluster 8.0.19/candidate
Store operation failed:
- None: Invalid track: 8.0.19
Full execution log: '/home/alex/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220615-120556.034291.log'
```

```
2022-06-15 12:05:56.034 Starting charmcraft version 1.7.1
2022-06-15 12:05:56.034 Raw pre-parsed sysargs: args={'help': False, 'verbose': False, 'quiet': False, 'trace': False, 'project_dir': None} filtered=['close', 'mysql-innodb-cluster', '8.0.19/candidate']
2022-06-15 12:05:56.034 General parsed sysargs: command='close' args=['mysql-innodb-cluster', '8.0.19/candidate']
2022-06-15 12:05:56.034 Couldn't find config file '/home/alex/Projects/Canonical/git/github.com/openstack-charmers/release-tools/charmcraft.yaml'
2022-06-15 12:05:56.035 Command parsed sysargs: Namespace(channel='8.0.19/candidate', name='mysql-innodb-cluster')
2022-06-15 12:05:56.035 System details: OSPlatform(system='ubuntu', release='20.04', machine='x86_64'); Environment: DESKTOP_SESSION='ubuntu', XDG_CURRENT_DESKTOP='ubuntu:GNOME'
2022-06-15 12:05:56.110 Retrieving credentials for 'charmcraft' on 'api.charmhub.io' from keyring 'SecretService Keyring'.
2022-06-15 12:05:56.145 HTTP 'POST' for 'https://api.charmhub.io/v1/charm/mysql-innodb-cluster/releases' with params None and headers {'Authorization': '<macaroon>', 'User-Agent': 'charmcraft/1.7.1 ubuntu/20.04 (x86_64) python/3.8.10'}
2022-06-15 12:05:56.294 Store operation failed:
- None: Invalid track: 8.0.19
2022-06-15 12:05:56.294 Traceback (most recent call last):
2022-06-15 12:05:56.294 File "/snap/charmcraft/978/lib/charmcraft/commands/store/store.py", line 140, in error_decorator
2022-06-15 12:05:56.294 return method(self, *args, **kwargs)
2022-06-15 12:05:56.294 File "/snap/charmcraft/978/lib/charmcraft/commands/store/store.py", line 322, in release
2022-06-15 12:05:56.294 self._client.request_urlpath_json("POST", endpoint, json=items)
2022-06-15 12:05:56.294 File "/snap/charmcraft/978/lib/charmcraft/commands/store/client.py", line 91, in request_urlpath_json
2022-06-15 12:05:56.294 response = super().request(method, self.api_base_url + urlpath, *args, **kwargs)
2022-06-15 12:05:56.294 File "/snap/charmcraft/978/lib/craft_store/base_client.py", line 174, in request
2022-06-15 12:05:56.294 return self.http_client.request(
2022-06-15 12:05:56.294 File "/snap/charmcraft/978/lib/craft_store/http_client.py", line 166, in request
2022-06-15 12:05:56.294 raise errors.StoreServerError(response)
2022-06-15 12:05:56.294 craft_store.errors.StoreServerError: Store operation failed:
2022-06-15 12:05:56.294 - None: Invalid track: 8.0.19
2022-06-15 12:05:56.294 Full execution log: '/home/alex/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220615-120556.034291.log'
```

Juju downloading various versions:

```
$ juju download mysql-innodb-cluster
Fetching charm "mysql-innodb-cluster" using "stable" channel and base "amd64/ubuntu/20.04"
Install the "mysql-innodb-cluster" charm with:
    juju deploy ./mysql-innodb-cluster_55f085e.charm
```

```bash
$ juju download mysql-innodb-cluster --channel=8.0/stable
Fetching charm "mysql-innodb-cluster" using "8.0/stable" channel and base "amd64/ubuntu/20.04"
Install the "mysql-innodb-cluster" charm with:
    juju deploy ./mysql-innodb-cluster_55f085e.charm
```

So the default track is 8.0/stable.

```bash
juju download mysql-innodb-cluster --channel=8.0.19/stable
Fetching charm "mysql-innodb-cluster" using "8.0.19/stable" channel and base "amd64/ubuntu/20.04"
Install the "mysql-innodb-cluster" charm with:
    juju deploy ./mysql-innodb-cluster_d307f37.charm
```

So juju can download the 8.0.19 charm.

# The issue:

juju and charmhub.io can 'see' and access the 8.0.19 track. charmcraft can't, and also won't allow the track/risk to be manipulated/closed. There's an inconsistency amongst the applications that access the charmhub.

(Also raised on LP for snapstore and juju: https://bugs.launchpad.net/juju/+bug/1978818)

**Comment by Roadmaster** [comment]
I removed the track from the "tracks available to release this snap with" list, but that does not remove channelmap entries made with the track.
[12:11 PM](https://chat.canonical.com/canonical/pl/kncy5d73ujbdieddtriusdr9mc)

When releasing a revision, we check that the given track name (if not latest) is registered for that snap; if it is, the channelmap entry with track/risk/branch is created. If the track name gets "unregistered", which is what I did, that does not magically then remove all channelmap entries that were created with it.
[12:12 PM](https://chat.canonical.com/canonical/pl/6kf97d5jzirzpcejda8nhtu5sa)

Juju and charmhub.io show the track because they're showing those channelmap entries; charmcraft does not because it checks the available tracks in the tracks table before organizing channelmap entries/releases under them (or at least I think it does).

In order for you to close those channels, I can temporarily add `8.0.19` back so charmcraft will be happy and let you `charmcraft close` those channels. Once that's done, we remove `8.0.19` again.

**Comment by facundobatista** [comment]
Hello! Thanks @ajkavanagh and @Roadmaster for all the info! Glad it's more clear now what's happening. 

We have two situations here, how to see the status properly and being able to close that channel.

Regarding the status, @Roadmaster is right, `charmcraft` is not showing the track at all because it's not in the list of "available channels". See the following raw response from Charmhub for a similar situation where is a release in `test1/candidate` but then `test` was "unregistered":

```
{'channel-map': [{'base': {'architecture': 'amd64',
                           'channel': '18.04',
                           'name': 'ubuntu'},
                  'channel': 'test1/candidate',
                  'expiration-date': None,
                  'progressive': {'paused': None, 'percentage': None},
                  'resources': [],
                  'revision': 13,
                  'when': '2022-06-15T16:14:09Z'},
                 ...
                ],
 'package': {'channels': [{'branch': None,
                           'fallback': None,
                           'name': 'latest/stable',
                           'risk': 'stable',
                           'track': 'latest'},
                          {'branch': None,
                           'fallback': 'latest/stable',
                           'name': 'latest/candidate',
                           'risk': 'candidate',
                           'track': 'latest'},
                          {'branch': None,
                           'fallback': 'latest/candidate',
                           'name': 'latest/beta',
                           'risk': 'beta',
                           'track': 'latest'},
                          {'branch': None,
                           'fallback': 'latest/beta',
                           'name': 'latest/edge',
                           'risk': 'edge',
                           'track': 'latest'},
                          {'branch': None,
                           'fallback': None,
                           'name': 'test-track/stable',
                           'risk': 'stable',
                           'track': 'test-track'},
                          {'branch': None,
                           'fallback': 'test-track/stable',
                           'name': 'test-track/candidate',
                           'risk': 'candidate',
                           'track': 'test-track'},
                          {'branch': None,
                           'fallback': 'test-track/candidate',
                           'name': 'test-track/beta',
                           'risk': 'beta',
                           'track': 'test-track'},
                          {'branch': None,
                           'fallback': 'test-track/beta',
                           'name': 'test-track/edge',
                           'risk': 'edge',
                           'track': 'test-track'}]},
 'revisions': [{'bases': [{'architecture': 'all', 'channel': '18.04', 'name': 'ubuntu'}],
                'created-at': '2021-03-05T16:19:34.877239',
                'errors': None,
                'revision': 13,
                'sha3-384': '309439e730c451277b32e03739101621d0d64f89a7fa93852bd140a5af022d2e6f41e4861ee27be980bcf2773e6e87a7',
                'size': 810689,
                'status': 'released',
                'version': '7.4a'},
                ...
                ]}
```

Charmcraft should do better in this case. For sure show the channel map corresponding to the unregistred track, but flagging it somehow... maybe instead of saying that the track is `test1`, it should say `test1 (unregistered)`.

On the other hand, Charmcraft is not doing anything special when asked to close the risk in the unregistered track. Charmhub is returning the exposed error. Remember that "closing a channel" is actually (at Charmhub's API level) "releasing revision None to that channel". So, if the track is unregistered so you cannot release to it, you won't be able to close channels either. @Roadmaster is there something Charmhub can do about this?

Thanks both again!

**Comment by facundobatista** [comment]
FTR, I opened #786 to track the improvement we can do in Charmcraft.

**Comment by ajkavanagh** [comment]
Hi @Roadmaster 

Thanks very much for the explanation; totally makes sense.

> In order for you to close those channels, I can temporarily add `8.0.19` back so charmcraft will be happy and let you `charmcraft close` those channels. Once that's done, we remove `8.0.19` again.

I think that would be very useful please; then I'll close the channels and we can then remove visibility of the track.  Much appreciated.

**Comment by facundobatista** [comment]
Wonderful that is being resolved. As the remaining work is tracked by #786, I'll close this. Thanks!!
