### ISSUE TITLE
Problem when install lib

### ISSUE THREAD

**Issue by SamirPS** [canonical/charmcraft#818]
Hello,

I follow the contributing guide, i create the venv and launch this command

```
pip install -r requirements-dev.txt -e .
```

but i get this error 

```
ollecting python-apt
  Using cached python-apt-0.7.8.tar.bz2 (49 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ho9wgpvu/python-apt_c394ef059dc34a8da30584768641c812/setup.py", line 6, in <module>
          from DistUtilsExtra.command import *
      ModuleNotFoundError: No module named 'DistUtilsExtra'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
what can i do ?

**Comment by facundobatista** [comment]
The `apt` lib needs to be installed separately. From the README:

```
    $ sudo apt install -y libffi-dev libapt-pkg-dev libssl-dev
    $ python3 -m venv env
    $ source env/bin/activate
    (env)$ pip install https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/python-apt/2.2.1/python-apt_2.2.1.tar.xz
    (env)$ pip install charmcraft
```

We should improve CONTRIBUTING instructions...

**Comment by SamirPS** [comment]
Thanks it's work, yeah need to improve the contributing instructions
