### ISSUE TITLE
charmcraft release failed for revision that is in the charmhub

### ISSUE THREAD

**Issue by ajkavanagh** [canonical/charmcraft#850]
charmcraft 2.0/stable (maybe 1.5/stable as the charm was packed/built on launchpad with 1.5/stable - note that all of the stable branches are built with 1.5/stable due to environment variable name changes and breakages in charmcraft).

Launchpad shows the error as:

```
Charmhub release failed: Resource 'nvidia-vgpu-software' doesn't have a released revision for charm with id 'LwR1wVMvBw6mDJaewfDaiCftUOD4yG0k' and revision 18
```

Manually attempting with charmcraft CLI (both 1.5/stable and 2.0/stable):

```
charmcraft --verbosity=trace release nova-compute-nvidia-vgpu --revision 18 --channel=latest/edge
2022-08-30 11:01:17.314 Starting charmcraft version 2.0.0                                                                                           
2022-08-30 11:01:17.314 Logging execution to '/home/alex/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220830-110117.313981.log'         
2022-08-30 11:01:17.314 Raw pre-parsed sysargs: args={'help': False, 'verbose': False, 'quiet': False, 'verbosity': 'trace', 'project_dir': None} filtered=['release', 'nova-compute-nvidia-vgpu', '--revision', '18', '--channel=latest/edge']                                                          
2022-08-30 11:01:17.314 General parsed sysargs: command='release' args=['nova-compute-nvidia-vgpu', '--revision', '18', '--channel=latest/edge']    
2022-08-30 11:01:17.314 Couldn't find config file '/home/alex/charmcraft.yaml'                                                                      
2022-08-30 11:01:17.315 Command parsed sysargs: Namespace(channel=['latest/edge'], name='nova-compute-nvidia-vgpu', resource=[], revision=18)       
2022-08-30 11:01:17.315 System details: OSPlatform(system='ubuntu', release='20.04', machine='x86_64'); Environment: DESKTOP_SESSION='ubuntu', XDG_CURRENT_DESKTOP='ubuntu:GNOME'                                                                                                                        
2022-08-30 11:01:17.401 Retrieving credentials for 'charmcraft' on 'api.charmhub.io' from keyring 'SecretService Keyring'.                          
2022-08-30 11:01:17.430 HTTP 'POST' for 'https://api.charmhub.io/v1/charm/nova-compute-nvidia-vgpu/releases' with params None and headers {'Authorization': '<macaroon>', 'User-Agent': 'charmcraft/2.0.0 ubuntu/20.04 (x86_64) python/3.8.10'}                                                          
2022-08-30 11:01:17.642 Store operation failed:
- api-error: Resource 'nvidia-vgpu-software' doesn't have a released revision for charm with id 'LwR1wVMvBw6mDJaewfDaiCftUOD4yG0k' and revision 18                                                                                                       
2022-08-30 11:01:17.643 Traceback (most recent call last):                                                                                          
2022-08-30 11:01:17.643   File "/snap/charmcraft/1033/lib/charmcraft/commands/store/store.py", line 140, in error_decorator                         
2022-08-30 11:01:17.643     return method(self, *args, **kwargs)                                                                                    
2022-08-30 11:01:17.643   File "/snap/charmcraft/1033/lib/charmcraft/commands/store/store.py", line 322, in release                                 
2022-08-30 11:01:17.643     self._client.request_urlpath_json("POST", endpoint, json=items)                                                         
2022-08-30 11:01:17.643   File "/snap/charmcraft/1033/lib/charmcraft/commands/store/client.py", line 91, in request_urlpath_json                    
2022-08-30 11:01:17.643     response = super().request(method, self.api_base_url + urlpath, *args, **kwargs)                                        
2022-08-30 11:01:17.643   File "/snap/charmcraft/1033/lib/craft_store/base_client.py", line 174, in request                                         
2022-08-30 11:01:17.643     return self.http_client.request(                                                                                        
2022-08-30 11:01:17.643   File "/snap/charmcraft/1033/lib/craft_store/http_client.py", line 166, in request                                         
2022-08-30 11:01:17.643     raise errors.StoreServerError(response)                                                                                 
2022-08-30 11:01:17.643 craft_store.errors.StoreServerError: Store operation failed:                                                                
2022-08-30 11:01:17.644 - api-error: Resource 'nvidia-vgpu-software' doesn't have a released revision for charm with id 'LwR1wVMvBw6mDJaewfDaiCftUOD4yG0k' and revision 18                                                                                                                               
2022-08-30 11:01:17.644 Full execution log: '/home/alex/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220830-110117.313981.log' 
```

And revisions show:

```
charmcraft revisions nova-compute-nvidia-vgpu
Revision    Version    Created at            Status                                                                                                 
18          18         2022-08-30T06:20:20Z  approved                                                                                               
17          17         2022-06-17T15:53:15Z  released                                                                                               
16          16         2022-05-16T14:34:21Z  approved                                                                                               
15          15         2022-05-05T23:59:12Z  released                                                                                               
14          14         2022-04-26T22:33:14Z  approved                                                                                               
13          13         2022-04-01T13:08:22Z  approved                                                                                               
12          12         2022-04-01T13:08:21Z  approved                                                                                               
11          11         2022-03-23T12:18:14Z  approved                                                                                               
10          10         2022-03-23T12:18:05Z  released                                                                                               
9           9          2022-02-28T11:50:40Z  approved                                                                                               
8           8          2022-02-28T11:50:39Z  approved                                                                                               
7           7          2022-02-25T11:54:28Z  approved                                                                                               
6           6          2022-02-25T11:54:27Z  approved                                                                                               
5           5          2022-02-22T17:40:21Z  approved                                                                                               
4           4          2022-02-22T17:37:25Z  approved                                                                                               
3           3          2022-02-22T11:21:28Z  approved                                                                                               
2           2          2022-02-22T11:20:45Z  approved                                                                                               
1           1          2022-01-31T15:34:17Z  approved
```

Bug may be on charmcraft or charmhub.io; (probably the latter), but hard to tell, so starting here.

**Comment by facundobatista** [comment]
Hello! Thanks for the report! 

Trying to understand the problem... question: may the latest charm revision have a `resource` declared in `metadata.yaml`, while previous revisions didn't? 

Thanks for the info!

**Comment by ajkavanagh** [comment]
Also the same on glance-simplestreams-sync charm:

```
Build status
[FULLYBUILT] Successfully built on [lcy02-amd64-040](https://launchpad.net/builders/lcy02-amd64-040)

Revision: abbae65b130db25357778893af699a664a8a5b95
Started 5 hours ago
Finished 5 hours ago (took 2 minutes, 20.6 seconds)
[buildlog](https://launchpad.net/~openstack-charmers/charm-glance-simplestreams-sync/+charm/charm-glance-simplestreams-sync.master.latest/+build/3031/+files/buildlog_charm_ubuntu_jammy_amd64_charm-glance-simplestreams-sync.master.latest_BUILDING.txt.gz) (15.0 KiB)
Charmhub release failed: Resource 'simplestreams' doesn't have a released revision for charm with id 'JWi9KLLwXR0HL08lxnpXdy7CxPh1hra1' and revision 80
```

```
charmcraft revisions glance-simplestreams-sync | head -n 10
Revision    Version    Created at            Status
80          80         2022-08-30T05:48:13Z  approved
79          79         2022-08-24T11:49:12Z  released
78          78         2022-07-25T15:33:13Z  released
77          77         2022-07-20T21:33:17Z  approved
76          76         2022-07-19T10:25:23Z  released
75          75         2022-07-06T15:18:15Z  approved
74          74         2022-07-05T15:22:14Z  approved
73          73         2022-06-28T21:18:18Z  approved
72          72         2022-06-22T15:20:55Z  approved
```

**Comment by facundobatista** [comment]
Let's keep talking about the original issue, otherwise it will be confusing. Do you have a resource declared `nvidia-vgpu-software`?

**Comment by ajkavanagh** [comment]
> Let's keep talking about the original issue, otherwise it will be confusing. Do you have a resource declared `nvidia-vgpu-software`?

They are both using resources, which probably implies they are both hitting the same issue.  `metadata.yaml` for nova-compute-nvidia-vgpu:

```yaml
cat metadata.yaml 
name: nova-compute-nvidia-vgpu
summary: Nvidia vGPU support for OpenStack Nova Compute
maintainer: OpenStack Charmers <openstack-charmers@lists.ubuntu.com>
description: |
  OpenStack Compute, codenamed Nova, is a cloud computing fabric controller.
  .
  This charm provides Nvidia vGPU support for Nova.
tags:
- openstack
series:
- jammy
subordinate: true
provides:
  nova-vgpu:
    interface: nova-vgpu
    scope: container
requires:
  juju-info:
    interface: juju-info
    scope: container
resources:
  nvidia-vgpu-software:
    type: file
    filename: nvidia-vgpu.deb
    description: |
      Proprietary NVIDIA vGPU host software (to be installed on compute nodes).
      .
      See https://docs.nvidia.com/grid/
```

However, the `nvidia-vgpu-software` resource declaration has been in the `metadata.yaml` right from the start, so this may mean that the charmhub.io (probably) has become more picky?  Which would probably mean that the launchpad recipes need to gain some additional functionality, as they may be unable to release to LP anymore?

**Comment by facundobatista** [comment]
Charmhub has a new functionality of auto-releasing resources for a charm release if it needs it and it can properly find which resource it is, e.g.:

- you release charm r17 with resource foo r14: `charmcraft release mycharm -r 17 -c stable --resource=foo:14`
- then, you release charm r18 but do not specify the resource: `charmcraft release mycharm -r 18 -c stable` -- in this case Charmhub will automatically include resource `foo` r14 in that release

So, this behaviour change can totally explain the new raised error.

But this is a good thing! Because it will mean that you never released the charm including a resource! So that release is actually "broken" (as the charm needs a resource but none is specified).

Maybe you should include a resource revision in that release?

**Comment by ajkavanagh** [comment]
@facundobatista That's both awkward and a good thing, but clearly not a charmcraft issue (rather a LP <-> charmhub issue).  If the 'auto' system works, then I can probably work around the issue, but the whole "auto" build system in LP is awkward when it comes to resources, as there isn't metadata in the charm to associate with a particular resource; rather it's left to outside the charm.  I'll raise a bug on launchpad and charmhub.io to discuss the issue.

Thanks for your help @facundobatista !
