### ISSUE TITLE
Misleading output for publish-lib when user has no permissions for the operation

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/charmcraft#937]
Hi!

I think the output when trying to publish a library you have no permissions for is not very helpful and that it would be advisable to show a permissions denied error to the users instead.
The current message is ` resource-not-found: Name nginx-ingress-integrator not found in the charm namespace`, which I find misleading.

The detailed log for that execution can be seen below:

````2022-12-01 17:48:14.382 Retrieving credentials for 'charmcraft' on 'api.charmhub.io' from keyring 'SecretService Keyring'.
2022-12-01 17:48:14.413 HTTP 'POST' for 'https://api.charmhub.io/v1/charm/libraries/nginx-ingress-integrator/db0af4367506491c91663468fb5caa4c' with params None and headers {'Authorization': '<macaroon>', 'User-Agent': 'charmcraft/2.1.0 ubuntu/22.04 (x86_64) python/3.8.10'}
2022-12-01 17:48:14.509 Store operation failed:
- resource-not-found: Name nginx-ingress-integrator not found in the charm namespace
2022-12-01 17:48:14.510 Traceback (most recent call last):
2022-12-01 17:48:14.510   File "/snap/charmcraft/1083/lib/charmcraft/commands/store/store.py", line 140, in error_decorator
2022-12-01 17:48:14.510     return method(self, *args, **kwargs)
2022-12-01 17:48:14.510   File "/snap/charmcraft/1083/lib/charmcraft/commands/store/store.py", line 386, in create_library_revision
2022-12-01 17:48:14.510     response = self._client.request_urlpath_json("POST", endpoint, json=payload)
2022-12-01 17:48:14.510   File "/snap/charmcraft/1083/lib/charmcraft/commands/store/client.py", line 91, in request_urlpath_json
2022-12-01 17:48:14.510     response = super().request(method, self.api_base_url + urlpath, *args, **kwargs)
2022-12-01 17:48:14.510   File "/snap/charmcraft/1083/lib/craft_store/base_client.py", line 174, in request
2022-12-01 17:48:14.510     return self.http_client.request(
2022-12-01 17:48:14.511   File "/snap/charmcraft/1083/lib/craft_store/http_client.py", line 166, in request
2022-12-01 17:48:14.511     raise errors.StoreServerError(response)
2022-12-01 17:48:14.511 craft_store.errors.StoreServerError: Store operation failed:
2022-12-01 17:48:14.511 - resource-not-found: Name nginx-ingress-integrator not found in the charm namespace
2022-12-01 17:48:14.511 Full execution log: '/home/arturo/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20221201-174814.095219.log'

**Comment by facundobatista** [comment]
Hello @arturo-seijas , thanks for the report!

It's a good idea, but it depends on the error sent from Charmhub. I opened [an issue in that project](https://bugs.launchpad.net/snapstore-server/+bug/1999430) to track the request.

Thanks again!

**Comment by arturo-seijas** [comment]
Hi! I've noticed the Charmhub issue you've opened has been fixed and released

**Comment by lengau** [comment]
I can no longer reproduce since the charmhub update.
